### ISSUE TITLE
Do not search files without heading

### ISSUE THREAD

**Issue by raphaelfeng** [alphapapa/org-ql#103]
It would be a similar fix for issue https://github.com/alphapapa/org-ql/issues/28
There was a fix to skip empty buffer b634647, it would be nice also to skip files without heading.
With skipping, if one of the files does not have a heading, the search would fail.

**Comment by alphapapa** [comment]
Please look more closely at https://github.com/alphapapa/org-ql/commit/b634647e466a7b25effddfbc535d61251c6629df

**Comment by alphapapa** [comment]
AFAIK the bug you describe is already fixed, so this report is invalid.  If you have more information, let me know.
