### ISSUE TITLE
Grouping by filename

### ISSUE THREAD

**Issue by kehoen** [alphapapa/org-ql#108]
Hello,

Thanks much for your work on this and other packages. Is there a way to group the query results by filename? I cannot seem to figure it out.

Also -- how do I save my views permanently? Closing/reopening emacs seems to delete my saved views.

Thanks.

**Comment by alphapapa** [comment]
Hi,

Thanks.

Grouping is handled by `org-super-agenda`.  See https://github.com/alphapapa/org-super-agenda#group-selectors

If your saved views are not persisting, that probably indicates that the `custom-set-variables` form is not configured correctly in your init files.

**Comment by kehoen** [comment]
Thanks! I got the grouping handled using auto-category (is there anyway to drop "category"?). 

Can you elaborate on the custom-set-variables?

**Comment by alphapapa** [comment]
> Thanks! I got the grouping handled using auto-category (is there anyway to drop "category"?).

You could edit the source code.

> Can you elaborate on the custom-set-variables?

This should be covered by Emacs documentation.

**Comment by kehoen** [comment]
Got it
