### ISSUE TITLE
Unstable sort messes up sorting with multiple predicates

### ISSUE THREAD

**Issue by koorogi** [alphapapa/org-ql#110]
If I use multiple sort predicates, items which are equal according to the first predicate are not necessarily sorted as expected according to the second predicate.  For example, with this input file:

```
* TODO [#B] task 1
  DEADLINE: <2020-04-21 Tue>
* TODO [#B] task 2
  DEADLINE: <2020-04-20 Mon>
```

Sorting by `'(priority deadline)` gives the following result:

```
  TODO [#B] task 1  in 3d 
  TODO [#B] task 2  in 2d 
```

That is, they are out of order with respect to their deadline.

It looks like an unstable sort is used when applying each predicate, meaning that for items that compare equal according to that predicate, there is no guarantee that the sorting already performed by other predicates will be maintained.

**Comment by alphapapa** [comment]
Sorting uses `-sort` which is stable: https://github.com/alphapapa/org-ql/blob/f4d7399e677904cdc7e220440610704e4bd668bc/org-ql.el#L1604

I can't reproduce the result you show.  With the same buffer contents, I eval'ed:

```el
(org-ql-search (current-buffer) '(todo) :sort '(priority deadline))
```
And I get:
```
  TODO [#B] task 2  in 1d 
  TODO [#B] task 1  in 2d 
```

**Comment by koorogi** [comment]
Hmm.  Indeed, I am not seeing it with that command either.

I have been trying out `org-super-agenda` along with `org-ql`, so I may have had some groups set when I ran this particular test.  I had assumed that `org-super-agenda` would retain the original relative order of items within the same group, but that appears to not be the case.  I suspect that's what really happened here.

Sorry for the noise.

**Comment by alphapapa** [comment]
> I had assumed that `org-super-agenda` would retain the original relative order of items within the same group, but that appears to not be the case.

That would be ideal, but as you can see in the source code, hash tables are sometimes used, which doesn't preserve ordering.  Most of the time it doesn't seem to be a problem.
