### ISSUE TITLE
Trouble with `org-ql-agenda--agenda`

### ISSUE THREAD

**Issue by georgewsinger** [alphapapa/org-ql#112]
After updating emacs I am getting

```
Symbol’s function definition is void: org-ql-agenda--agenda
```

Specifically evaluating a 

```
(query-ql my-list nil 0 9)
```

yields

```
Debugger entered--Lisp error: (void-function org-ql-agenda--agenda)
```

**Comment by AloisJanicek** [comment]
`org-ql-agenda` was removed in `v.0.3` https://github.com/alphapapa/org-ql#03
You need rewrite your search using `org-ql-search`.

**Comment by georgewsinger** [comment]
When switching `org-ql-search` I get 

```
helm-M-x-execute-command: Cannot open load file: No such file or directory, peg
```

**Comment by georgewsinger** [comment]
After installing `peg`, and then `ov`, I now get

```
helm-M-x-execute-command: Opening directory: No such file or directory, /home/george/org
```

Hmm.

**Comment by alphapapa** [comment]
@AloisJanicek Thanks.

@georgewsinger Please reinstall the packages.  The problem is with your Emacs configuration.
