### ISSUE TITLE
Error launching org-ql-search (buffer-"query"-don't group)

### ISSUE THREAD

**Issue by Ypot** [alphapapa/org-ql#116]
I always use pleasantly org-rifle, because it works and org-ql gives me errors. But as org-ql and org-sidebar seem to have interesting options, and to be the favored ones by the developer (alphapapa), I may share in their respective githubs the problems that are impeding me from using those packages.

On Windows I get this error with a org-ql-search:
`helm-M-x: Symbol’s value as variable is void: crm-local-completion-map`

**Comment by alphapapa** [comment]
You haven't said what Emacs version you're using.  You probably need to upgrade it.

**Comment by Ypot** [comment]
Hi.
I am using GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)
 of 2019-08-29

**Comment by Ypot** [comment]
Ok. I updated your packages and now it seems to work :-)

Should I update dependencies manually too? Or is it automatic when updating your packages from MELPA?

**Comment by alphapapa** [comment]
Dependencies only get upgraded automatically when the required version number changes, which doesn't happen often.  MELPA packages are not well synchronized.  You should generally manage package versions yourself.  See discussions on reddit.com/r/emacs for more info.
