### ISSUE TITLE
How to define a custom view in my init.el file prompting the user for tags?

### ISSUE THREAD

**Issue by riclage** [alphapapa/org-ql#118]
Is there a way to read tags from the user in the same way `read-number` or `read-string` allows?

I would like to have a custom view pre-defined where I ask the user for a tag (or list of tags) and use that in a `org-ql-search` query.

Is that possible? Thanks!

**Comment by alphapapa** [comment]
This question is not about `org-ql`, so it would be more appropriate to ask on, e.g. the org-mode mailing list, reddit.com/r/orgmode, etc.

**Comment by riclage** [comment]
Indeed, apologies for asking it here. I actually asked it elsewhere (and got an answer) and forgot to update it here: https://emacs.stackexchange.com/questions/58365/how-to-prompt-user-for-tags-and-use-the-result-in-a-org-ql-search-function

**Comment by alphapapa** [comment]
@riclage FYI, you may find this new feature interesting: https://github.com/alphapapa/org-ql/blob/master/examples/defpred.org
