### ISSUE TITLE
Show content of matched headlines

### ISSUE THREAD

**Issue by dorneanu** [alphapapa/org-ql#123]
Hi! I think this is an awesome tool. I've played with some examples and this is what I want to achieve:

```
* Books
** Book 1 
*** Quote 1                                      :quote:
      #+begin_quote
      bla
      #+end_quote 
*** Quote 2                                      :quote:
      #+begin_quote
      ble
      #+end_quote 
** Book 2 
*** Quote 1                                      :quote:
      #+begin_quote
      blu
      #+end_quote 
```

I want to extract all quotes tagged by `quote` *and* also show the content. What I've done so far (in current buffer and *grouped by parent*):

```
Query: tags: quote
```

I do get the matched headlines (which contain tag `quote`) but how do I actually *show* the content of headlines? For me that'd be pretty useful since depending of the content of the quote I might add additional tags.

Thanks in advance. 

PS: I'm not that familiar with (e)lisp.

**Comment by alphapapa** [comment]
Hi,

What you seem to be asking for is not implemented.  More flexible and featureful display of results is planned for the future.  You can see some other discussion about this in other issues filed here.
