### ISSUE TITLE
Improve my configuration

### ISSUE THREAD

**Issue by bepolymathe** [alphapapa/org-ql#125]
Hi @alphapapa 

Thank you for this wonderful tool that is org-ql. I would like to improve my configuration for a particular project. The one is organized in a folder that is not my "org" folder and I don't want to include it. It seems possible that adding a new search perenne in org-ql view but I don't quite understand how. 

If for example I would like to search in a single folder (or even recursively) for entries with a given tag or todo. Something like that in my .spacemacs ? 

```
(org-ql-select "~/folder/"
  '(todo)
  :action #'org-get-heading)
```

**Comment by alphapapa** [comment]
Please see the docstrings and usage instructions: https://github.com/alphapapa/org-ql#org-ql-search

**Comment by reyman** [comment]
@bepolymathe Something like that could help you, i search all org file with `#+FILETAGS: :PROJECT:`, ang auto-group by category (filename of org file)

I actually search how to improve this by using double grouping : a) group by filename + group by priority. I'm not sure this is actually possible.  

```
(let* ((files (->> (f--files "~/Notes/2ndBrain" (equal (f-ext it) "org")))))
  (org-ql-search files
    '(and (todo)
          (tags "PROJECT"))
:super-groups '((:auto-category t))))
```

**Comment by alphapapa** [comment]
> I actually search how to improve this by using double grouping : a) group by filename + group by priority. I'm not sure this is actually possible.

You would need to write group definitions manually rather than using `auto-` groups.
