### ISSUE TITLE
org-ql--plain-query does not recognise olp: predicate

### ISSUE THREAD

**Issue by yantar92** [alphapapa/org-ql#128]
Recipe: run `(org-ql--plain-query "olp:koh")`.

Expected return value: `(olp "koh")`.
Observed return value: `(regex "olp:koh")`.

As a consequence, I am not able to search by outline path in `helm-org-ql`.

The problem seems to be in the following lines in `org-ql--plain-query`:

```
(peg-parse-string ...
                           (predicate-with-args (substring predicate) ":" args)
                           (predicate-without-args (substring predicate) ":")
...)
``` 

According to comment in peg.el, a rule (NAME PEX...) in `peg-parse-string` must have either a list, vector, or a string in place of PEX. This is not the case in two rules above.

**Comment by alphapapa** [comment]
Thanks for the ECM, however I can't reproduce it:
```el
(org-ql--plain-query "olp:koh")  ;;=> (olp "koh")
```

**Comment by yantar92** [comment]
I cannot reproduce anymore, so closing this.
