### ISSUE TITLE
Trouble with link queries with org-ql-search

### ISSUE THREAD

**Issue by gdindi** [alphapapa/org-ql#131]
Hi,
I can't successfully perform queries involving links. I am simply trying to find all the entries in an org buffer wich have a link to a particular entry. Say that the buffer contains:
```
* A

* B 
rietaniet [[id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3][C]] ristena

* C
:PROPERTIES:
:ID:       fcf8d4b1-1d29-4305-95d5-dc506b4103e3
:END:
```

If I invoke org-ql-search, I choose to restict it to "buffer" and I enter

`link:"id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3"`

Then RET twice (for don't group and default sort), the org-ql view that I get is empty.

I have tried different sintaxes for the query, with and without s-exps:

`link:"id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3"`
`link:"fcf8d4b1-1d29-4305-95d5-dc506b4103e3"`
`(link "id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3")`
`(link "fcf8d4b1-1d29-4305-95d5-dc506b4103e3")`
`(link :target "id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3")`
`(link :target "fcf8d4b1-1d29-4305-95d5-dc506b4103e3")`

And the result is always an empty view.

What am I doing wrong?

Thanks!

**Comment by alphapapa** [comment]
It works for me.  See this example:
```el
(with-current-buffer (generate-new-buffer "test")
  (org-mode)
  (insert "* A

* B 
rietaniet [[id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3][C]] ristena

* C
:PROPERTIES:
:ID:       fcf8d4b1-1d29-4305-95d5-dc506b4103e3
:END:
")
  (org-ql-select (current-buffer) '(link "id:fcf8d4b1-1d29-4305-95d5-dc506b4103e3")))
;; => ((headline (:raw-value "B" :begin 6 :end 10 :pre-blank 0 :contents-begin 11 :contents-end 11 ...)))
```

**Comment by gdindi** [comment]
Hi,
Thanks for your answer. 
Your example works, but using org-ql-search instead of org-ql-select, produced what seemed to be an empty org-ql view. Further investigation shows that the view is not empty, but the text is not visible. This seems to be related to the theme I am using, since all is OK without using any color theme. 

I am sorry for wasting your time with this.

**Comment by alphapapa** [comment]
Thanks for your follow-up!
