### ISSUE TITLE
Documentation: mention caching in org-ql-select and friends descriptions

### ISSUE THREAD

**Issue by mskorzhinskiy** [alphapapa/org-ql#132]
Some time ago I wrote a few actions for org-ql-select and put a lot of various logic there. I noticed that these actions are acting very strange. It seems to me that internal logic of org-ql caching results into not executing actions if they are already were executed on the same headers.

Example code:
```
(defun org-ql-test (files query)
  (org-ql-select files query
    :action (lambda ()
              (message ">> rasmi >> Hello there!")
              nil)))

(org-ql-test (org-agenda-files) '(and
                                  (level 1)
                                  (tags "travel")
                                  (tags "current")))
```

Executing (org-ql-test) will print messages first time I execute it and will do nothing every next time. 

This seems logical and correct behaviour of course, but I think this is worth mentioning in documentation. It may be save a little bit of time for the next guy not paying attention how this package works. :-)

**Comment by alphapapa** [comment]
Probably a good idea.  Thanks.
