### ISSUE TITLE
"in X days" prioritizes deadline--allow option to based on scheduled?

### ISSUE THREAD

**Issue by rieje** [alphapapa/org-ql#134]
Currently using the [WIP branch](https://github.com/alphapapa/org-ql/tree/wip/issue-79) with fix to sorting with org-ql-block.

It seems regardless of sorting by `deadline` or by `scheduled`, the agenda context for time-sensitive tasks e.g. "`in 144d`" is prioritized based on deadline if a task has both a scheduled date and a deadline date. Is it possible to show "in X days" based on scheduled instead? This is useful for example for monthly tasks that eventually expire.

**Comment by alphapapa** [comment]
> I guess you can do it by `:sort (scheduled deadline)` to show X days until scheduled date instead of deadline.

Did you try using that?

**Comment by rieje** [comment]
Sorry, I mean relative dates. Updated.

**Comment by alphapapa** [comment]
Sorry, I was unclear, which is why I edited my comment.  Changing the sort order has no effect on the displayed relative date.  That is hard-coded at the moment.  Please see other discussions here about future plans to make formatting more flexible.
