### ISSUE TITLE
Org-ql bookmark with buffer-files as function

### ISSUE THREAD

**Issue by tpeacock19** [alphapapa/org-ql#148]
I'm unable to save a `org-ql-view` bookmark if the `buffer-files` property is a function (i.e. `org-agenda-files`). I believe the below would provide a fix.

```diff
diff --git a/org-ql-view.el b/org-ql-view.el
index b0f47a3..bcef322 100644
--- a/org-ql-view.el
+++ b/org-ql-view.el
@@ -528,13 +528,16 @@ dates in the past, and negative for dates in the future."
 (defun org-ql-view--bookmark-make-record ()
   "Return a bookmark record for the current Org QL View buffer."
   (cl-labels ((file-nameize
-               (b-f) (or (buffer-file-name b-f)
+               (b-f) (or (when (file-regular-p b-f) b-f)
+                         (buffer-file-name b-f)
                          (when (buffer-base-buffer b-f)
                            (buffer-file-name (buffer-base-buffer b-f)))
                          (user-error "Only file-backed buffers can be bookmarked by Org QL View: %s" b-f))))
     (pcase-let* ((plist (org-ql-view--plist (current-buffer)))
                  ((map :buffers-files) plist))
       ;; Replace buffers with their filenames, and signal error if any are not file-backed.
+      (when (functionp buffers-files)
+        (setq buffers-files (funcall buffers-files)))
       (setf plist (plist-put plist :buffers-files
                              (cl-etypecase buffers-files
                                (string buffers-files)

```

**Comment by alphapapa** [comment]
I think there are two approaches we could take here, and I'm not sure which is best:

1.  As you suggest, use the "expanded" form, the function's return value.  The problem with this is that, when opening a link, if the function would return a different value than the one it returned when the view was bookmarked, that new value would not be reflected in the opened view.  So if a user added a file to his agenda files list, it would not be taken into account, and this would not necessarily be apparent to the user, which could cause some items to be unknowingly omitted from the view.
2.  Handle functions or special values accordingly.  See, e.g. `org-ql-view--complete-buffers-files` and `org-ql-view--contract-buffers-files`.  This would probably take more work and might require further adjustments in the future if those expectations change.

What do you think?  Thanks.

**Comment by tpeacock19** [comment]
I could make the case that those variables do not change so often agenda-files and the like. But that would be bias from within my own workflow of using fewer files. I'm sure users of org-roam that include them in agenda-files would have a drastically different experience.

Although as you said it would take more work, I think #2 is the more complete solution. It would also be closer to the experience of bookmarks elsewhere on the internet, where it takes you to the same url regardless of change in content (in the most basic of senses).

**Comment by alphapapa** [comment]
Yeah, the value of `org-agenda-files` basically never changes for me, but I think we should handle it properly when it does.

I think this needs a bit more thought and design.  Maybe `function` values need to be handled, or even lambdas.  

I'll probably defer working on that more comprehensive fix.  In the meantime, what's the current status?  If you search your agenda files and bookmark the view, does it work or not?  (Sorry, I've gotten a bit confused with all these recent changes.)  Maybe it still needs to be expanded properly to the list of files as you suggest.

**Comment by tpeacock19** [comment]
As of 60b457eea4b5d72a4b0b8e7df7c617c1b21ae99f,  Trying to  bookmark an org-ql-view that has :buffer-files as either a function, or a list of file names, does not work.

**Comment by alphapapa** [comment]
> I think this needs a bit more thought and design. Maybe `function` values need to be handled, or even lambdas.

For future reference (including my own), this is probably not the way to go.  Now that links have been implemented, their parameters need to not include arbitrary code like lambdas.  I've done what I can to make them safe (see https://github.com/alphapapa/org-ql/commit/a5d48868808a8ba59db360466f1c1b1060db16c5 and https://github.com/alphapapa/org-ql/commit/5e790c48acb91b5969f0147f591fdcd7dfecc7bd), but as much as possible, we should avoid eval'ing or calling any functions passed as arguments to `org-ql-search`.  

For the `buffers-files` argument, instead, it should accept one or more buffers, filenames, or one of a few special values with predefined meanings, like `org-agenda-files`.

**Comment by alphapapa** [comment]
@tpeacock19 Okay, I *think* that fixes everything.  Please let me know how it works for you.  Thanks, as always.

**Comment by tpeacock19** [comment]
A list of file names still throws an error. Adding this, I believe fixes. But aside from that, I believe everything else is fixed. 

```diff
diff --git a/org-ql-view.el b/org-ql-view.el
index 843211e..173fcbe 100644
--- a/org-ql-view.el
+++ b/org-ql-view.el
@@ -544,7 +544,8 @@ dates in the past, and negative for dates in the future."
 (defun org-ql-view-bookmark-make-record ()
   "Return a bookmark record for the current Org QL View buffer."
   (cl-labels ((file-nameize
-               (b-f) (or (buffer-file-name b-f)
+               (b-f) (or (when (stringp b-f) b-f)
+                         (buffer-file-name b-f)
                          (when (buffer-base-buffer b-f)
                            (buffer-file-name (buffer-base-buffer b-f)))
                          (user-error "Only file-backed buffers can be bookmarked by Org QL View: %s" b-f))))

```

**Comment by alphapapa** [comment]
Okay, I think that should finally do it.  It seems to work for me.  Thanks again for your help.
