### ISSUE TITLE
Tags no longer visible in ql-views

### ISSUE THREAD

**Issue by tpeacock19** [alphapapa/org-ql#150]
I can no longer see tags in the org-ql-view buffer (since the commit 359a280d11d54c940125f11d7be6a93f8c0c1095. 

I can call `(org-ql--tags-at (copy-marker (org-element-property :begin (org-element-at-point))))` on the first point of a headline and the correct values are returned. However, if I run an org-ql-search on the same buffer I get `(org-ql-nil org-ql-nil)`.

I think this is because `org-ql--tags-at` is called from a temp buffer. which results in both the buffer cache and the `(looking-at org-ql-tag-line-re)` to fail. But I haven't been able to confirm.

To be clear, filtering by local or inherited tags works; its just the formatted element no longer includes them.

**Comment by alphapapa** [comment]
Oops, thanks for catching that.  That should fix it, and seems to for me.  Please let me know if it does for you.

**Comment by tpeacock19** [comment]
This seems to work, after opening and viewing files which I assume is to build the cache? Either way, I think it is okay to keep this closed.

**Comment by alphapapa** [comment]
> This seems to work, after opening and viewing files which I assume is to build the cache?

Sorry, what exactly do you mean?  Files can't be searched unless they're already open in Emacs.  Is there something unexpected still happening?

**Comment by tpeacock19** [comment]
Yes I believe it is because the `org-ql--tags-at` function is not resetting the position when searching for tags. Even though you've set it now to be called with the correct buffer, its running from wherever the current cursor is. For example, in the below image I've placed cursor at the start of the final heading. It results in all headings showing a `three` tag.

![2020-11-11-06:06:27_screenshot](https://user-images.githubusercontent.com/6407145/98815366-3d20af80-23e4-11eb-854d-714f084aa1fb.png)

**Comment by alphapapa** [comment]
That was a silly mistake on my part.  That should do it, and I just verified that it works as expected now.  Thanks for your patient help with these issues.

**Comment by alphapapa** [comment]
BTW, I'd like to credit you in the changelog for this version.  Should I use "@tpeacock19" or something else?

**Comment by tpeacock19** [comment]
That would be great, tpeacock19 works, I appreciate it.
