### ISSUE TITLE
org-link is displayed entirely in a dynamic block

### ISSUE THREAD

**Issue by jbriquet** [alphapapa/org-ql#153]
In my workflow, I have many org-link in the headings which are displayed in their raw form when trying the dynamic block feature. I wonder if it's possible to display only the link label ? I know that org-ql-view does it already.

Here are the package versions I am using.
org-mode : 9.4
emacs: 27.1
org-ql: org-ql-20201116.1052

Here is an example of what I am seeing : 
```
#+TITLE: Work notes
#+TODO: TODO NEXT WAITING IN_PROGRESS | DONE
* Summary

** TODO headline has an org-link [[http:www.google.com][google]] 

** summary 
  
   #+BEGIN: org-ql :query (todo)
   | Heading                                                 | Todo | P |
   |---------------------------------------------------------+------+---|
   | [[headline has a org-link \[\[http:www.google.com\]\[google\]\]][headline has a org-link [[http:www.google.com][google]​]​]] | TODO |   |
   #+END:  
```

**Comment by alphapapa** [comment]
Thanks, I think that should fix it.
