### ISSUE TITLE
"Error: Variable binding depth exceeds max-specpdl-size"

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/org-ql#157]
FYI, to anyone who encounters this message:

It's a byte-compile error that happens intermittently.  It's caused by some recent changes that I made regarding macro expansion.  I'm working on it.

In the meantime, the code in question actually works, despite the error.  And if the file from which the error is signaled is byte-compiled again (e.g. view the directory containing the file in Dired, and press `B` on the uncompiled `.el` file), compilation seems to complete without error.

So the package remains fully usable, all tests pass, etc.  And the most recent stable release, 0.5, doesn't have this compilation issue.

**Comment by alphapapa** [comment]
Fixed in https://github.com/alphapapa/org-ql/commit/014d49f4162bf34b2265fe87302c66d0aac57d71

**Comment by pkazmier** [comment]
I can confirm this is now fixed for me too. Thanks!
