### ISSUE TITLE
Feature Requestion: dedicated targets

### ISSUE THREAD

**Issue by notuntoward** [alphapapa/org-ql#158]
The giant org file I need to parse is full of [dedicated targets](https://orgmode.org/manual/Internal-Links.html).  It would be great if `org-ql` could search for them -- like it can for headings or todos -- as well as to search internal links to them.

**Comment by alphapapa** [comment]
Would something like this work?
```el
(org-ql-defpred (dedicated-target dt) (name)
  "Search for a dedicated target named NAME (i.e. \"<<NAME>>\"."
  :normalizers ((`(,predicate-names ,name)
                 `(regexp ,(concat "<<" name ">>")))))
```

**Comment by notuntoward** [comment]
Yes, that looks for the elisp side of it.  Is it too much bother to put it into the non-sexp query language too?

**Comment by alphapapa** [comment]
The macro does that already.  After evaluating that code, you can search for `dt:NAME`.

**Comment by notuntoward** [comment]
Oh, excellent.  Thanks very much!

**Comment by alphapapa** [comment]
You're welcome.  See the defpred tutorial for more: https://github.com/alphapapa/org-ql/blob/master/examples/defpred.org
