### ISSUE TITLE
Use getopts instead of getopt

### ISSUE THREAD

**Issue by Apteryks** [alphapapa/org-ql#165]
Hello!

https://github.com/alphapapa/org-ql/blob/5fab48e2cd0ed0f37cf81816349a61219688436e/makem.sh#L985

Relies on the 'getopt' util being available in the environment.  As the script already specifies its interpreter as Bash, could it instead rely on Bash's own getopts?

Thank you for your consideration.

**Comment by alphapapa** [comment]
Hello,

First, this discussion belongs on the makem.sh repo: https://github.com/alphapapa/makem.sh

Anyway, no, the behavior of getopt and getopts are very different.  The script uses GNU getopt for a reason.  It should be present, or easily installable, on any GNU system, and it's also installable with Homebrew on other Unix systems.

**Comment by Apteryks** [comment]
Hi! Apologies for posting this to the wrong tracker.

Ah, you are right, the GNU getopt (or the one provided by util-linux, as on my system) support long GNU style options (--option), which doesn't seem to be the case for the POSIX (usually shell bulitin) getopts. I remember reading this piece of advice here: https://mywiki.wooledge.org/BashFAQ/035#getopts which discouraged the use of `getopt`.

Anyway, since there seems to be a valid need for its features, its use can be justified. Closing, thank you.

**Comment by alphapapa** [comment]
>  I remember reading this piece of advice here: https://mywiki.wooledge.org/BashFAQ/035#getopts which discouraged the use of `getopt`.

Yes, I think I've seen that before.  It says:

> There is a version of getopt(1) in util-linux, but you should not use it. Why not? Because you would need to write special safety-checking code to ensure that you've actually got this nonstandard getopt, and then you would still need to write a fallback option processor for when you don't have it. So you're doing twice as much work and getting no significant benefits for it. 

Alternatively, I could declare that my script is designed to use getopt, which is readily available, if not installed by default, on any Linux or Unix system, and then enjoy the significant benefits of using it, without having to rewrite the same, tedious option parsing code in every script.  It seems absurd to me that in 2020 the only ways to parse long options and combined short options and flags with optional arguments are to use getopt or to rewrite convoluted shell code in every script, and that there seems to be some kind of general aversion to using getopt.  getopt works great, so I use it, and I think more people should.  I'm not very interested in writing minimalistic, purely POSIX-compatible shell scripts when there are better tools like Bash and getopt.  (Hey, at least it's not Python.  (Not that I dislike Python, but it's a much larger dependency than Bash and getopt.))

Well, that's my two cents, anyway.  I assume that Guix has getopt packaged?

**Comment by Apteryks** [comment]
For the record: yes, the `getopt` command is available on Guix; it is provided by the `util-linux` package. AFAICT, the only other getopt in use nowadays is in the form of a C procedure, provided by the GNU C library (glibc).

**Comment by alphapapa** [comment]
Thanks.
