### ISSUE TITLE
org-agenda-prefix-format

### ISSUE THREAD

**Issue by jave** [alphapapa/org-ql#170]
I have this configuration:

```
  (defun jv-todoinfo()
    (let
        ((numchilds 0))

      (save-mark-and-excursion
        (org-narrow-to-subtree)
        (setq numchilds (- (length
                         (--filter (eq 'todo it)
                                   (progn
                                     (let ((parsetree (org-element-parse-buffer 'headline))) 
                                       (org-element-map parsetree 'headline 
                                         (lambda (hl) (org-element-property :todo-type hl))))))) 1))

        ;;im not sure why the widen is needed, but otherwise agenda generating breaks
        (setq numchilds (if (= 0 numchilds) "" numchilds))
        (widen))
      numchilds))


  (setq org-agenda-prefix-format
        '((agenda . " %i %-20:c%?-12t% s")
          (timeline . "  % s")
          (todo . " %i %3(jv-todoinfo)| %-20:c")        
          (tags . " %i %-12:c")
          (search . " %i %-12:c"))
        )
```

Org-ql  doesnt respect org-agenda-prefix-format though.

I guess thats not a big problem, except when you close a task in a org-ql agenda like view, org-agenda-prefix-format suddenly shows up briefly, which is visually jarring.

So I suggest orq-ql should either support org-agenda-prefix-format, or ignore it completely.

**Comment by jave** [comment]
Example structure:
** TODO [#A]  a task with subtasks
*** TODO subtask 1
*** TODO subtask 2


what it looks like in the original agenda

    2| orgscratch:         TODO [#A]  a task with subtasks

what it looks like in an org-ql block:
  TODO [#A] a task with subtasks 

When you close it:

    1| orgscratch:         DONE [#A] a task with subtasks


And when you then further refresh the agenda, the task vanishes, which is normal, because its closed. Hope that makes it clearer.

**Comment by yantar92** [comment]
See #83

**Comment by jave** [comment]
duplicate of #83
