### ISSUE TITLE
Selectable Group Headings

### ISSUE THREAD

**Issue by dustinlacewell** [alphapapa/org-ql#18]
It would be interesting if group headings were selectable like the actual org headings. They would call some function provided in the configuration of the super groups under `:handler` or something. What I would use this for is potentially invoking other super-agendas, or possibly something like `helm-projectile-find-file-dwim`.

**Comment by alphapapa** [comment]
I think what you're asking is already provided by `org-super-agenda-header-map`.  See https://github.com/alphapapa/org-super-agenda#tips

**Comment by dustinlacewell** [comment]
Yeah seems like you could implement whatever you wanted with that. I guess group-heading links are not considered useful enough to have very simplified support via the group settings DSL.
