### ISSUE TITLE
void-function with-peg-rules

### ISSUE THREAD

**Issue by jkitchin** [alphapapa/org-ql#185]
I am unable to use helm-org-ql, I get an error about a void function called with-peg-rules. I do seem to have a peg library, but it does not have a with-peg-rules in it. The command works, but after I type about 3 characters I get a backtrace.

My library seems old and is from elpa. Is there some other library that provides this? I am using emacs 27.1.90.

**Comment by yantar92** [comment]
> My library seems old and is from elpa.

Can you try to update it to the latest version manually? Looking at the
library page [1], the latest version of elpa should have
`with-peg-rules` (it is literally in the readme).

[1] https://elpa.gnu.org/packages/peg.html

**Comment by jkitchin** [comment]
It is weird

Package peg is available obsolete. I was finally able to install it, and then it works. I will close it for now, this is mostly likely some thing on my end.

```
     Status: Available Obsolete from gnu -- Install
    Archive: gnu
    Version: 1.0
    Summary: Parsing Expression Grammars in Emacs Lisp
   Requires: emacs-25
Required by: org-ql-20201213.1358
   Homepage: https://elpa.gnu.org/packages/peg.html
 Maintainer: Stefan Monnier <monnier@iro.umontreal.ca>
     Author: Helmut Eller <eller.helmut@gmail.com>
Other versions: 20150708.641 (installed), 1.0 (installed).
```
