### ISSUE TITLE
Suitable replacement for org-id?

### ISSUE THREAD

**Issue by vv111y** [alphapapa/org-ql#188]
I searched around github & r/emacs, couldn't find a clear answer. How do they compare performance wise? 
Any other relevant pros/cons to be aware of?  

Thnking some more: a hashtable makes sense as the number of headings and file sizes goes up. At least the search is reduced to one file. Also persisting the hashtable does help as the IDs should not change in the long term. As well, at least for my use case, the headings are not likely to move between files. 

Thank you for making this package, this is great.

**Comment by akirak** [comment]
@vv111y IDs are stored in `org-id-locations-file`, so it's good on performance and resistant to moving entries across files. Org provides built-in commands for refiling and archiving subtrees, so it is necessary to support moving headings to other files.

**Comment by alphapapa** [comment]
As Akira said, Org's existing ID cache seems sufficient, so I don't see any reason to reimplement it in this package.

> Thank you for making this package, this is great.

Thanks, I'm glad it's useful to you.
