### ISSUE TITLE
Any way to find every org files having a property like #+hugo_tags?

### ISSUE THREAD

**Issue by bbigras** [alphapapa/org-ql#198]
Is there a way to get a list of all the org files having some property like #+hugo_tags?

```org
#+title: Writing Hugo blog in Org (File Export)
#+date: 2017-09-10
#+author: Kaushal Modi
#+hugo_tags: hugo org

* First heading within the post
```

**Comment by akirak** [comment]
@bbigras You can simply perform a string/regexp search for that purpose. You don't need this package.
