### ISSUE TITLE
Unable to use org-ql anymore: Symbol’s function definition is void: with-peg-rules

### ISSUE THREAD

**Issue by falematte** [alphapapa/org-ql#199]
After a Melpa update I started getting this error whenever I try a search.

**Comment by otesuji** [comment]
Symbol’s function definition is void: -on in my case. can't use anymore since update!

**Comment by alphapapa** [comment]
As you can see, the code in this package has not changed recently.  Can you reproduce the problem in a clean Emacs configuration?

**Comment by otesuji** [comment]
Sorry but it is working again. I've updated other packages only. Strange.

**Comment by akirak** [comment]
`dash-functional` was merged with `dash` and became obsolete. `-on` is now part of dash.

**Comment by falematte** [comment]
I have updated melpa and dash functional. Still the same error... Any tips?

**Comment by alphapapa** [comment]
> As you can see, the code in this package has not changed recently. Can you reproduce the problem in a clean Emacs configuration?

**Comment by alphapapa** [comment]
See also #191. You could search the closed issues for the symbol and find that issue.
