### ISSUE TITLE
Out-of-date dependences (dash-functional)

### ISSUE THREAD

**Issue by jmay** [alphapapa/org-ql#209]
From https://github.com/magnars/dash.el/blob/master/dash-functional.el

This package has been absorbed, and is therefore made obsolete, by the `dash' package, version 2.18.0.

Should be removed from dependencies for bufler.

org-ql should be updated to specify latest dash and remove dash-functional.

**Comment by basil-conto** [comment]
See #197.

**Comment by alphapapa** [comment]
Fixed with #197.  Thanks.
