### ISSUE TITLE
possible to return results in file headings? 

### ISSUE THREAD

**Issue by mediapathic** [alphapapa/org-ql#215]
I note that org-ql does not return results that are outside of org headers, such as `#+filetags:` and the like. I presume that this is inherent in the architecture, but I would quite like to be able to search against filetags, so consider this either a query or a feature request, depending on how hard it is to implement. 

EDIT: after finding #57 I believe this is actually a request for a documentation improvement. :) it seems that filetags are supported, but I would like an example of syntax using them, because nothing I am trying is working.

**Comment by alphapapa** [comment]
No special syntax is required; filetags are simply tags which are inherited when `org-tag-inheritance` is enabled.  Please see the commit which fixed the bug, in which you can see a test data file and the related tests: https://github.com/alphapapa/org-ql/commit/9f5bbeb3f246079dce8cbff11ef365b2a0ef2ff1
