### ISSUE TITLE
Sorting results with org-ql-block

### ISSUE THREAD

**Issue by acosmicjoke** [alphapapa/org-ql#218]
I noticed that `org-ql-block` doesn't allow sorting the query results. It doesn't accept a `:sort` argument and ignores the value of `org-agenda-sorting-strategy` . I use org-ql only through custom agenda commands, and lacking this feature makes it pretty inconvenient. `org-ql-block` seems to be using `org-ql-select` internally, which already knows how to sort results, so this sounds pretty easy to implement.

**Comment by alphapapa** [comment]
Please see #79.
