### ISSUE TITLE
Use org-ql without aggregating results in agenda

### ISSUE THREAD

**Issue by muntean-alex** [alphapapa/org-ql#219]
Maybe more of a request.

Is it possible to use org-ql to search org-agenda-files (or a number of files) and grab the headings with their elements based on a propriety (for example, all timestamped items in the last 7 days, or, it could be a tag)
* item1
   SCHEDULED: <2020.06.03>
* item2
from all files, and aggregate them in a (new) plain org file?
I would like to continue to use other functions (like columnview) to summarize the results.

**Comment by alphapapa** [comment]
You can write code to do this if you wish.  Simply write a function to take the results of `org-ql-select` and do whatever you like with them.

**Comment by muntean-alex** [comment]
Am I mistaken in thinking that when using the results I lose the subheadings?
For example, I would like to use ADDED (my own addition), SCHEDULED and CLOSED subheadings which do no longer appear as such in org-agenda. That's where I get stuck.

**Comment by alphapapa** [comment]
I don't understand what you're asking.

Anyway, I can't offer this kind of detailed guidance in the issue tracker.  You seem to need more general help with Elisp and Org, not just with org-ql specifically.  Please use an appropriate forum, like the Org mailing list, Reddit, etc.  If you use r/orgmode, you can tag my username there and I might be able to offer some advice: u/github-alphapapa.
