### ISSUE TITLE
Can one use dynamic blocks to query other files than the one containing the block?

### ISSUE THREAD

**Issue by wuqui** [alphapapa/org-ql#234]
Is it somehow possible to query other files than the current one using a dynamic block? Just like with `org-ql-search`? I'm thinking of something like this:

```
#+BEGIN: org-ql :query "tags:foo" :from "~/org/bar.org"
```

Ideally, it would be amazing to be able to pass in a directory path as well and have it search all org files contained in it. This would be extremely useful to me.

By the way, what an awesome package -- thanks a lot! 🤓

**Comment by alphapapa** [comment]
Please see #151.

> By the way, what an awesome package -- thanks a lot! nerd_face

Thanks, I'm glad it's useful to you.
