### ISSUE TITLE
Warnings: "Warning (bytecomp): pcase pattern `(,(or 'tags-inherited 'inherited-tags 'tags-i 'itags)) shadowed by previous pcase pattern"

### ISSUE THREAD

**Issue by arozbiz** [alphapapa/org-ql#240]
I'm getting this `compile-log` warning: ```Warning (bytecomp): pcase pattern `(,(or 'tags-inherited 'inherited-tags 'tags-i 'itags)) shadowed by previous pcase pattern```

I've searched through all my emacs code for `tags-inherited` and `tags-i` and that only appears in `org-ql`, so I'm assuming it's an issue with this package?

`(emacs-version)` return: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-07-05`

My org-ql version is `20210713.233`

**Comment by alphapapa** [comment]
Please be sure to use the search function before reporting a new issue.  https://github.com/alphapapa/org-ql/issues?q=is%3Aissue+is%3Aopen+shadowed

**Comment by arozbiz** [comment]
Apologies!
