### ISSUE TITLE
How to get dynamic blocks to work

### ISSUE THREAD

**Issue by baracunatana** [alphapapa/org-ql#243]
Hi

After reading the documentation, I tried the following dynamic block:

```
#+BEGIN: org-ql :query "todo: " :columns (heading)

#+END: 
```

However, nothing happens and I have no idea how to "run" the dynamic block. What am I missing here? is there any particular configuration needed for this?

Thanks,

**Comment by alphapapa** [comment]
Please see the Org manual: https://orgmode.org/manual/Dynamic-Blocks.html
