### ISSUE TITLE
How to customize org-super-agenda-groups and faces inside org-ql-block

### ISSUE THREAD

**Issue by Ieremies** [alphapapa/org-ql#244]
First, thanks for the package! It is no fricking useful!!!

I'm trying to set some blocks in my agenda, and I'm running into some problems:

![image](https://user-images.githubusercontent.com/36969625/129462451-86822499-8b88-465b-93ca-11fc5f28e660.png)

First, as we can in the above image, on the block "Open" there is also the org-super-agenda grouping. I know with normal org-agenda blocks, we can set `org-super-agenda-groups` to `nil` in order to disable in a block. How can I do this with `org-ql-block`?

Second, also exemplified in the image, the results in the block have different color than the ones in the agenda. Those in the agenda have the `org-agenda-face` applied to then, but I can find a face to customize those in the block. How could I change their color?

Last, but no least, I really want some way to show the category of a task in that new block. Preferably, in the same way org-agenda does. Is there a way?

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I'm glad it's useful to you.

> First, as we can in the above image, on the block "Open" there is also the org-super-agenda grouping. I know with normal org-agenda blocks, we can set org-super-agenda-groups to nil in order to disable in a block. How can I do this with org-ql-block?

Please see the documentation for the variable `org-agenda-custom-commands`.  It's a little complicated, but it describes how to bind variables around each block, which you can use to do that.

> Second, also exemplified in the image, the results in the block have different color than the ones in the agenda. Those in the agenda have the org-agenda-face applied to then, but I can find a face to customize those in the block. How could I change their color?

I guess you'd need to write a little code to do that.  I'm not sure if that face's not being set is an oversight or if something changed in Org that org-ql needs to be updated for.

> Last, but no least, I really want some way to show the category of a task in that new block. Preferably, in the same way org-agenda does. Is there a way?

For now, you'd have to customize the formatting function.  Please see the relevant issue in this tracker about custom formatting.

Obrigado.  :)

**Comment by Ieremies** [comment]
Sorry for the late reply.

> Please see the documentation for the variable org-agenda-custom-commands

I got it working! I think I messed up the parenthesis the first time and thought it wouldn't work with `org-ql-block`.

> I guess you'd need to write a little code to do that. I'm not sure if that face's not being set is an oversight or if something changed in Org that org-ql needs to be updated for.

I will look into that, but I'm not yet so well versed in the almighty Elisp to adventure myself on the word of faces. What I think is happening is org-agenda does not apply any face to entries by default. Since my agenda only show items with deadlines, schedules, clocked and so, and those have special faces, when `org-ql-block` shows items without any of those, it defaults to no-face.

![image](https://user-images.githubusercontent.com/36969625/130452423-1022594a-d4d7-43ef-bd0c-dc5c59722bb8.png)
(First is clocking, second has a deadline but third has none, so no face is aplied.)

> For now, you'd have to customize the formatting function. Please see the relevant issue in this tracker about custom formatting.

Yep, found it #44 .

> Obrigado. :)

Eu que agradeço!!

**Comment by alphapapa** [comment]
> I will look into that, but I'm not yet so well versed in the almighty Elisp to adventure myself on the word of faces. What I think is happening is org-agenda does not apply any face to entries by default. Since my agenda only show items with deadlines, schedules, clocked and so, and those have special faces, when `org-ql-block` shows items without any of those, it defaults to no-face.

Ah, that makes sense.  I think you figured it out.  :)  Thanks.
