### ISSUE TITLE
Duplicate entries for buffers-or-files produces duplicate items in result

### ISSUE THREAD

**Issue by ahmed-shariff** [alphapapa/org-ql#261]
Related to discussion in #258  

If there a duplicate entries in the buffers-or-files, they are not filtered out, resulting in duplicate entries in the result. 

To reproduce:
if content of `file1.org` are:
```org
* heading 1 in file1
* heading 2 in file1
```

```elisp
(let ((file-name "file1.org"))
  (with-current-buffer (find-file-noselect file-name)
    (org-ql-select (list (current-buffer) file-name) '(level 1)
      :action (lambda () (substring-no-properties (org-get-heading t t t t))))
    ;;; result: ("heading 1 in file1" "heading 2 in file1" "heading 1 in file1" "heading 2 in file1")
    (org-ql-select (list file-name file-name) '(level 1)
      :action (lambda () (substring-no-properties (org-get-heading t t t t))))
    ;;; result: ("heading 1 in file1" "heading 2 in file1" "heading 1 in file1" "heading 2 in file1")
    ))
```

**Comment by alphapapa** [comment]
This doesn't seem like a problem to me.  Why should it be the responsibility of `org-ql-select` to remove these duplicate filenames rather than that of the calling code?  And doing it in `org-ql-select` would mean imposing that cost on every call, even when it's not necessary.

**Comment by ahmed-shariff** [comment]
Sounds good to me :)
