### ISSUE TITLE
ts ignores timestamps with time ranges

### ISSUE THREAD

**Issue by mz-pdm** [alphapapa/org-ql#265]
When a timestamp contains a time range, e.g. `<2021-12-13 Mon 13:00-13:55 +1w>`, then `ts` and friends don't match it. When I change org-ql-regexp-part-ts-time as

```
(setq org-ql-regexp-part-ts-time
        (rx " " (repeat 1 2 digit) ":" (repeat 2 digit)
            (optional "-" (repeat 1 2 digit) ":" (repeat 2 digit))))
```

then it works fine.

**Comment by alphapapa** [comment]
Please see #237.  Thanks.
