### ISSUE TITLE
How to show column headers with org-ql-query ?

### ISSUE THREAD

**Issue by tupini07** [alphapapa/org-ql#266]
I apologize if this is addressed elsewhere, and I just didn't see it. I have an org file with reviews of some books I've read: each headline corresponds to one book, and properties denote details of the book. I'm able to successfully query the headlines and properties, but the resulting table does not show the name of the columns. This is the query I'm using:

```elisp
#+begin_src elisp
(org-ql-query
  :select '(list (substring-no-properties (org-get-heading t t))
                 (property "AUTHOR")
                 (property "RATING")
                 (property "SERIES")
                 (property "NUM_IN_SERIES")
                 (property "FINISHED_AT")
                 (property "FORMAT")
                 (property "ISBN"))
  :from (buffer-file-name)
  :where '(done))
#+end_src
```

And this is a screenshot of the resulting table:

![image](https://user-images.githubusercontent.com/3422347/147501011-1524847d-9c9e-4d30-80d5-5d0bc2377736.png)

Is there any way to get the column names to show automatically?

btw, thanks for making this great tool!

**Comment by alphapapa** [comment]
Hello,

This question is less about org-ql and more about Org tables in general.  It would be better to ask on, e.g. old.reddit.com/r/orgmode, so anyone could answer quickly.  Anyway, something like this would probably do it:

```el
(append (list "TITLE"
              "AUTHOR"
              "RATING"
              "SERIES"
              "NUM_IN_SERIES"
              "FINISHED_AT"
              "FORMAT"
              "ISBN")
        (org-ql-query
          :select '(list (substring-no-properties (org-get-heading t t))
                         (property "AUTHOR")
                         (property "RATING")
                         (property "SERIES")
                         (property "NUM_IN_SERIES")
                         (property "FINISHED_AT")
                         (property "FORMAT")
                         (property "ISBN"))
          :from (buffer-file-name)
          :where '(done)))
```

> btw, thanks for making this great tool!

Thanks, I'm glad it's useful to you.
