### ISSUE TITLE
Could "closed" include ":LAST_REPEAT:"?

### ISSUE THREAD

**Issue by schemar** [alphapapa/org-ql#267]
First of all, thank you so much for org-ql. It's a tremendous help.

I was wondering whether the following was possible:
List all tasks that were done last week, including recurring tasks.

My use-case is that I want to see all tasks that I had done last week in my weekly review. At the moment, I use `closed` and that does not include recurring tasks that I finished in the given time frame.

I don't want to use `ts` (or `ts-inactive`), even though those would list the tasks due to the `LOGBOOK` entry. There are too many false positives (especially non-TODOs) that come with the timestamps.

**Comment by alphapapa** [comment]
Hi Martin,

> First of all, thank you so much for org-ql. It's a tremendous help.

Thanks, I'm glad that it's useful to you.

> I was wondering whether the following was possible: List all tasks that were done last week, including recurring tasks.
> 
> My use-case is that I want to see all tasks that I had done last week in my weekly review. At the moment, I use `closed` and that does not include recurring tasks that I finished in the given time frame.
> 
> I don't want to use `ts` (or `ts-inactive`), even though those would list the tasks due to the `LOGBOOK` entry. There are too many false positives (especially non-TODOs) that come with the timestamps.

Yes, a logbook predicate is planned.  Please see #192 and #245.  If those don't seem to do specifically what you need, please comment there and I'll try to include what you need.  Thanks.
