### ISSUE TITLE
Can we see the filename in a Org-ql-view as in helm-org-ql

### ISSUE THREAD

**Issue by proudot** [alphapapa/org-ql#273]
Hi there! I like how helm-org-ql show filenames before the header like org-agenda

```
myfilename: TODO my task
```

Can one display it too in an org-ql-view buffer ?

Thanks again for the wonderful package!

**Comment by proudot** [comment]
I have found the solution here https://github.com/alphapapa/org-ql/issues/23 .

**Comment by alphapapa** [comment]
This will be easier when I merge the `taxy-org-ql-view` branch, which will let you easily configure custom columns in the search view.
