### ISSUE TITLE
Possible to search in several directories?

### ISSUE THREAD

**Issue by AtomicNess123** [alphapapa/org-ql#276]
I would like to be able to search all TODOs beyond Agenda files from several org buffers on my disk. Is this possible? Thanks!

**Comment by dmgerman** [comment]
Either 

1. Create a function that returns a list of the files that you want to scan. 
2. Create a list of files you want to scan

Use this as the first parameter to org-ql-select

**Comment by AtomicNess123** [comment]
Is org-ql-select a interactive function? Doesn't seem so. Thanks!

**Comment by alphapapa** [comment]
@dmgerman Thanks for offering your help here.  :)

@AtomicNess123  Please see the org-ql manual's section on commands.
