### ISSUE TITLE
add buffer-file-name to 'element 

### ISSUE THREAD

**Issue by dmgerman** [alphapapa/org-ql#288]
the 'element list does not include the buffer-file-name

Since org-ql accepts various files in the from clause, it would be useful to append the buffer-file-name to the parsed element that org returns

alternative, it could be added to element-with-markers (which has the filename, but embedded into the hd-org-marker and org-marker

I could create a pull-request if this is of interest.

**Comment by alphapapa** [comment]
Well, since this is already covered by using `element-with-markers` and `(marker-buffer (org-element-property ELEMENT :org-marker))`, I'm not sure what would be gained by adding the buffer file name to the `element` option, other than reducing performance and increasing memory usage.

**Comment by dmgerman** [comment]
Thanks. I didn't know how to extract that file name from the marker. However, there is a bit of an inconsistency of how those filenames are created. See below. When I pass org-agenda-files, the filenames are relative. When I pass a list of files, the result is a full path. org-agenda-files contains the full paths (I checked).

    #+begin_src emacs-lisp :results value
    (mapcar (lambda (entry)  (marker-buffer (org-element-property :org-marker entry ))
                )
            (org-ql-select (org-agenda-files)
              '(todo "NEXT")
                            :action 'element-with-markers
                            )))
    #+end_src
    
    #+RESULTS:
    | actionable.org | csc503.org | home.org | home.org | home.org | home.org | jp.org | jp.org | jp.org | ww.org |
    
    #+begin_src emacs-lisp :results value
    (mapcar (lambda (entry)  (marker-buffer (org-element-property :org-marker entry ))
                )
            (org-ql-select (list "/tmp/rip.org")
              '(todo "NEXT")
                            :action 'element-with-markers
                            )))
    #+end_src
    
    #+RESULTS:
    | /tmp/rip.org |

**Comment by alphapapa** [comment]
Note that you're not passing `org-agenda-files`  but `(org-agenda-files)`, i.e. the value returned by the function.

**Comment by dmgerman** [comment]
I wrote the following callback:

    (org-ql-select (org-agenda-files)
              '(todo "NEXT")
              :action '(let
                           ((element (org-element-headline-parser (line-end-position))))
                         (list (car element) (plist-put (cadr element) :filename buffer-file-name)))
              )

that does that I needed. Perhaps it can be added to the documentation.

One issue I ran into, that you might be aware: if the action is a function name, this function is compiled and (I think) kept into a cache. So I pass a function called do_something to the action, and then I change the body of do_something, the new changes are ignored. 

I think this is fine, but I think it would be a good idea to mention in the documentation.

thanks again for your patience and the great work of org-ql

**Comment by alphapapa** [comment]
> I wrote the following callback:
> 
> ```
> (org-ql-select (org-agenda-files)
>           '(todo "NEXT")
>           :action '(let
>                        ((element (org-element-headline-parser (line-end-position))))
>                      (list (car element) (plist-put (cadr element) :filename buffer-file-name)))
>           )
> ```
> 
> that does what I needed. Perhaps it can be added to the documentation.

Again, why not use `element-with-markers` and extract the filename with `(buffer-file-name (marker-buffer ...))` when needed?
> 
> One issue I ran into, that you might be aware: if the action is a function name, this function is compiled and (I think) kept into a cache. So I pass a function called do_something to the action, and then I change the body of do_something, the new changes are ignored.

> I think this is fine, but I think it would be a good idea to mention it in the documentation.

This is already documented: https://github.com/alphapapa/org-ql#caching

> thanks again for your patience and the great work of org-ql

Thanks for the kind words.  I'm glad it's useful to you.

**Comment by dmgerman** [comment]
> Again, why not use element-with-markers and extract the filename with (buffer-file-name (marker-buffer ...)) when needed?

ok, now I see that my mistake was not to use "buffer-file-name". I was only extracting the buffer-name. This now works as I expected it. I am adding an example of how to use it in case somebody needs it:

    (mapcar (lambda (entry) (buffer-file-name (marker-buffer (org-element-property :org-marker entry )))
                ) 
           (org-ql-select (org-agenda-files)
              '(todo "TODO")
                            :action 'element-with-markers
                            ))


I'll close the issue. Thanks again.
