### ISSUE TITLE
Query normalization limit exceeds on src predicate

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-ql#293]
Hello,

~It seems that `src` predicate does not terminate.~ I encounter the following error whenever I run a query containing `src`:

> org-ql--normalize-query: Query normalization limit exceeded: QUERY:(src)

You can reproduce the error using the following snippet:

```emacs-lisp
(org-ql-select (current-buffer) '(src))
```

I am on the master branch (`0.7-pre`).

**Comment by alphapapa** [comment]
Thanks for reporting this, Akira.  I'll try to get to it soon.

**Comment by alphapapa** [comment]
Finally fixed.  Thanks for your patience.
