### ISSUE TITLE
[BUG?] Timestamp with interval are not included

### ISSUE THREAD

**Issue by Cletip** [alphapapa/org-ql#300]
Hello,

Sorry, I can't think of a better title. 
A better description would be: headings with an interval and not a specific date/time are not found with the "ts-a" predicate.

Step to reproduce and to better describe the problem: let these two elements (in a org agenda file)

```
* something 1
<2022-08-31 Wed 15:00-16:00>

* something 2
<2022-08-31 Wed 15:00>
```

Then, the following query: 

```
(org-ql-select (org-agenda-files)
    '(and
      (not (done))
      (ts-active :to today)
      )
    )
```

or with the org-ql-search command and the query 
`(and (not (done)) (ts-active :to today))`

As you can see, only the heading with no interval is returned.

Thank you very much in advance for your answers

PS : don't hesitate to ask me more details, like my version of org-ql or something else

**Comment by alphapapa** [comment]
Hello,

FYI, AFAIK, in Org terms, a timestamp like `<2022-08-31 Wed 15:00-16:00>` includes a "range," not an "interval."  

For more about this issue, please see #237.
