### ISSUE TITLE
Search for `src` finds only first occurrence

### ISSUE THREAD

**Issue by johanwk** [alphapapa/org-ql#304]
Using `org-ql-query`, I want to find which sections contain source blocks in a specified language.

```
    (org-ql-query
      :select '(list (substring-no-properties (org-get-heading t t))
                     (src :lang "ttl"))
    ... etc.
```

However, only the first source block is considered, i.e., the result is `t` only if a `ttl` block is the _first_ source block under the heading.

Maybe the problem is in `org-ql-defpred`, which seems to return once a source block with non-matching language is encountered. Gives up too soon?

**Comment by johanwk** [comment]
This change still leaves something to be desired. If you want to combine a search for a language with regexps in the source block, it will return nil if the regexps aren't present in the _first_ block to match the language.

**Comment by alphapapa** [comment]
@johanwk Thanks for reporting this.  The fix should be fairly simple, and I'll try to get to it soon.

**Comment by johanwk** [comment]
Great!

I'm very impressed with how efficient and smart org-ql really is. Wish I had discovered it sooner.

**Comment by alphapapa** [comment]
Finally fixed.  Thanks for your patience.
