### ISSUE TITLE
Allow for regex in tag search

### ISSUE THREAD

**Issue by SterlingHooten** [alphapapa/org-ql#305]
I see from https://github.com/alphapapa/org-ql/issues/145 that there's the possibility for tag hierarchy support, but this seems to require explicitly denoting tags as a group prior to executing a query.

What I'd like is to be able to match tags like "emacs" and "emacs_org" with a wildcard. The default org search can do this with `{^emacs.*}` but it looks like org-ql's syntax only accepts strings for tag searches.

Is there a way to search through tags using regular expressions instead?

**Comment by akirak** [comment]
@SterlingHooten There is `tags-regexp` predicate. I think it is exactly what you want.

**Comment by SterlingHooten** [comment]
Thank you! That's exactly it, don't know how I missed that in the documentation.
I was able to use `helm-org-ql-agenda-files` with query `tags*:^emacs.*` to retrieve headings tagged with both "emacs" and "emacs_org". Likewise `org-ql-search` returned the same results with the sexp version `(tags-regexp "^emacs.*")`.

**Comment by alphapapa** [comment]
@akirak Thanks for helping with this.

@SterlingHooten Is there anything else to be done on this issue?

**Comment by SterlingHooten** [comment]
@alphapapa No, you can close it, thanks!
