### ISSUE TITLE
Buttercup test suite never terminates (apparently due to recent changes in Buttercup)

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/org-ql#309]
See https://github.com/alphapapa/org-ql/pull/237#issuecomment-1298538032.  If anyone would like to dig into this, feel free.  After all the work I put into the test suite, to have it suddenly stop working for no apparent reason is quite frustrating.

Another possibility is that https://github.com/alphapapa/makem.sh needs to be updated for some internal change in Buttercup, but that seems unlikely given the way Buttercup is behaving, going into an infinite loop and never terminating.

It's also possible that I'm actually experiencing this bug: https://github.com/jorgenschaefer/emacs-buttercup/issues/220  But after several minutes of waiting, it seems like it ought to have completed by now, especially since no recursive structures are used, so setting `print-circle` and the like shouldn't be necessary.

**Comment by akirak** [comment]
The test suite of org-ql terminates (and succeeds) with my framework: https://github.com/akirak/org-ql/actions/runs/3627336948/jobs/6117132359

I thought buttercup tests in my projects didn't terminate, but that doesn't seem to be the case. I may further investigate this issue.

**Comment by alphapapa** [comment]
Well, thankfully, this problem seems to be gone with the latest versions of all packages and the latest `makem.sh`.  I've no idea what caused it, but it doesn't matter now.  Thanks for checking into it, Akira.
