### ISSUE TITLE
Plain query doesn't handle multiple conditions correctly

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-ql#314]
Hello, I'm using `org-ql-completing-read`, but it doesn't seem to handle multiple conditions now.

Single condition seems to work:

```emacs-lisp
ELISP> (org-ql--query-string-to-sexp "todo: ")
(todo)
```

However, if multiple conditions are specified in a plain query, all queries other than the first one become a `rifle` query with the first letter eliminated:

```emacs-lisp
ELISP> (org-ql--query-string-to-sexp "todo: test")
(and
 (todo)
 (rifle "est"))
```

```emacs-lisp
ELISP> (org-ql--query-string-to-sexp "todo: ts:on=today")
(and
 (todo)
 (rifle "s:on=today"))
```

```emacs-lisp
ELISP> (org-ql--query-string-to-sexp "sample text")
(and
 (rifle "sample")
 (rifle "ext"))
```

It once behaved differently from this. Is this the current expected behavior?

**Comment by alphapapa** [comment]
That's not what I get.  I get this:
```el
(org-ql--query-string-to-sexp "todo: test")
;; (and (todo) (rifle "test"))

(org-ql--query-string-to-sexp "todo: ts:on=today")
;; (and (todo) (ts :on "today"))

(org-ql--query-string-to-sexp "sample text")
;; (and (rifle "sample") (rifle "text"))
```

**Comment by akirak** [comment]
There was a recent update in `peg.el`: https://github.com/emacsmirror/peg/commit/90c9004a8347209f94a37c8d9506425721098402

After the update, test cases for the plain query parsing fail. It was the same phenomenon as I described above:

>   Plain query parsing
    Negated terms  Expected `(org-ql--query-string-to-sexp "todo: !todo:CHECK,SOMEDAY")' to be `equal' to `(and (todo) (not (todo "CHECK" "SOMEDAY")))', but instead it was `(and (todo) (todo "CHECK" "SOMEDAY"))' which does not match because: (list-elt 2 (proper-lists-of-different-length 3 2 (todo "CHECK" "SOMEDAY") (not (todo "CHECK" "SOMEDAY")) first-mismatch-at 0)). (28.73ms)
    Regexp predicates (11.42ms)
    Timestamp-based predicates (28.56ms)
    To-do predicates (8.93ms)
    Compound queries  Expected `(org-ql--query-string-to-sexp "todo:SOMEDAY ts-a:from=2020-01-01,to=2021-01-01")' to be `equal' to `(and (todo "SOMEDAY") (ts-a :from "2020-01-01" :to "2021-01-01"))', but instead it was `(and (todo "SOMEDAY") (regexp "s-a:from=2020-01-01"))' which does not match because: (list-elt 2 (proper-lists-of-different-length 2 5 (regexp "s-a:from=2020-01-01") (ts-a :from "2020-01-01" :to "2021-01-01") first-mismatch-at 0)). (3.78ms)

So the issue was due to an update in peg.

**Comment by alphapapa** [comment]
This should be fixed now.  Please let me know if it works for you.

**Comment by akirak** [comment]
It works with the latest version of peg from ELPA. Thanks!
