### ISSUE TITLE
What is the expected output of the test suite?

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-ql#315]
Hello, I'm trying to investigate #314 by myself, and I want to run the test suite for this package.

For some reasons, I am trying to use my own framework instead of makem.sh to run tests. It allows me to run tests with an older version of buttercup, so it's useful in the current situation.

I ran the test suite with the following command line:

```sh
emacs -l buttercup -L . -f buttercup-run-discover
```

and the test stopped with the following message:

> After 0 kbd macro iterations: buttercup-run failed: ""

and the screenshot:

![wayshot-20221204-153945](https://user-images.githubusercontent.com/6270544/205478271-d2193e95-1392-4408-ae72-929748738e29.png)

I ran the test with Emacs 28.1 and 28.2, and buttercup is v1.25, which is older than the version of the last time when your CI was green. Is this the correct output of the test?

**Comment by alphapapa** [comment]
IIRC you need to run Emacs in script mode, not interactive mode, which is the default.

**Comment by akirak** [comment]
@alphapapa Thanks, you are right. That was my mistake.
