### ISSUE TITLE
Set title of org-ql-block blocks

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/org-ql#32]
https://www.reddit.com/r/emacs/comments/cnrt2d/orgqlblock_integrates_orgql_into_org_agenda/ewtt9ob/

**Comment by mz-pdm** [comment]
As a workaround, I remove "Query:" lines in org-agenda-finalize-hook. They are not useful at all in org-ql-blocks, I create intelligible titles using org-super-agenda groups. (Having to define a single-entry super agenda group for just that purpose is overkill, though.)

**Comment by jschwab** [comment]
I just tried `org-ql` and did not like that I could not easily replace the Query: with an intelligible title.  So I agree this is a nice idea for an enhancement.

**Comment by alphapapa** [comment]
@jschwab Note that in the `org-ql-search` command, you can set a title to be displayed in the header.

For `org-ql-block`, I should be able to fix this soon.

**Comment by alphapapa** [comment]
That should do it!

**Comment by jschwab** [comment]
Thanks for implementing this.  It works nicely.

**Comment by jschwab** [comment]
I just tried [this example](https://github.com/alphapapa/org-ql/blob/master/examples.org#stuck-projects-block-agenda) again (after updating to melpa 20190928.519) and it no longer seems to work.  That is, the query is displayed instead of org-ql-block-header.

**Comment by alphapapa** [comment]
Thanks, I'll look into it.

**Comment by alphapapa** [comment]
@jschwab I accidentally omitted that feature when I refactored.  Should be fixed now.  Thanks for letting me know.
