### ISSUE TITLE
Exclude scheduled based on time

### ISSUE THREAD

**Issue by jonolo6** [alphapapa/org-ql#321]
Hi All, 

I'm trying to build a query that excludes items that are scheduled in the future - considering time. I.e. if the time currently is 9:05 and I have an item scheduled at 9:10 I do not want it to show, but items scheduled 'before' (in time) 9:05 should show. 

Here's the code I've written specifically lines (0)(1)(2)(3). Hardcoding the timestamp (2) actually seems to work as expected. I just can't get any of the 'automated' ways to work (0)(1)(3).

I'm a newbie in Emacs/Lisp so I'm probably doing something fundamentally wrong here...

``` emacs-lisp
(let ((date (current-time-string)))
(org-ql-search
(org-agenda-files)
'(and (todo)
 (or
  (scheduled :to date) ;; (0)
  ;; (scheduled :to (format-time-string "%Y-%m-%d %H:%M"))  ;; (1)
  ;; (scheduled :to "2023-01-12 09:05") ; (2)
  ;; (scheduled :to (current-time-string)) (3)
  (not(scheduled))
 )
(not (descendants (todo)))
(not (todo "HOLD" "SOMEDAY"))
(not (tags "personal_" "personal"))
)
:sort '(date reverse todo reverse priority)
:super-groups '(
(:name "Set Priority" :not(:priority("A" "B" "C" "D" "E" "F")))
(:name "Priority A" :priority "A")
(:name "Due" :deadline past :deadline today)
(:name "Time Sensitive" :tag("time_sensitive_" "time_sensitive"))
(:name "Critical Path" :tag("critical_path_" "critical_path"))
(:name "Quick" :tag("quick_" "quick"))
(:name "Inbox (organise)" :tag("inbox_" "inbox"))
(:name "Main" :tag("main_" "main"))
(:name "Focus" :tag("focus_" "focus"))
(:name "Priority B" :priority "B")
(:name "Priority C" :priority "C")
(:name "Priority D" :priority "D")
))
)

```

**Comment by alphapapa** [comment]
Hello,

> I'm a newbie in Emacs/Lisp so I'm probably doing something fundamentally wrong here...

Yes, that's all the problem is.  The search expression is quoted, so the forms `date`, `(format-time-string "%Y-%m-%d %H:%M")`, and `(current-time-string)` are not evaluated before being passed to `org-ql`.

Please see https://www.gnu.org/software/emacs/manual/html_node/elisp/Quoting.html and https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

**Comment by jonolo6** [comment]
Oooh! This is nice!

Apologies for wasting your time! But big thanks for showing me. I've got it working now!
