### ISSUE TITLE
Is it possible to show the org-agenda-like week view with timelines?

### ISSUE THREAD

**Issue by panmengguan** [alphapapa/org-ql#322]
Thank you for this great package! It provides an elegant interface to filter out the org-agenda items and I feels that it is much faster than the vanilla org-agenda. According to examples lists here [examples](https://github.com/alphapapa/org-ql/blob/af18eac2b80b2f56c135f37fcbdcce19fbc34b65/examples.org), it can provide views for TODOs. And I wonder is it possible to for the org-ql to generate the default org-agenda-like week view (`C-c a a`) with timelines? Like the following figure.

![image](https://user-images.githubusercontent.com/4384206/213213349-a5d6fd6b-f2cd-470f-bc37-404b2f3f60a0.png)

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I'm glad it's useful to you.

No, the `org-ql-view` does not support all of Org Agenda's features yet.  But I do hope to add features like that in the future (depending on Org Agenda's own development).

In the meantime, you may find it helpful to use `org-ql-block` sections in Org Agenda views, to get some features from both systems.  See: https://github.com/alphapapa/org-ql#function-org-ql-block
