### ISSUE TITLE
Can't install helm-org-ql or org-ql on emacs wsl2

### ISSUE THREAD

**Issue by rgri** [alphapapa/org-ql#329]
Running Emacs 27.1 installed through WSL2 on a windows host, adding the `use-package` block specified in the install instructions to init.el fails to install helm-org-ql.

After `M-x helm-org-ql` the minibuffer returns:
`Symbol's function definition is void: byte-run--set-speed`
The same output is returned when installing just org-ql.

**Comment by alphapapa** [comment]
Hello,

These packages are not specific to an OS or platform.  You seem to have a problem with your Emacs installation, which I can't help you with here.  Please seek help in an appropriate forum.
