### ISSUE TITLE
Changelog mentions removed commands

### ISSUE THREAD

**Issue by progfolio** [alphapapa/org-ql#335]
The docs/changelog mention the `org-ql-find-heading` and `org-ql-find-path` commands, but they are not present in the codebase.

commit:  aadddc4

**Comment by alphapapa** [comment]
Apparently I forgot to remove them from the docs here: https://github.com/alphapapa/org-ql/commit/5768c685adc7c6e85c17cfec358aa8a0e368310b  Thanks.

**Comment by alphapapa** [comment]
Well, `org-ql-find-heading` still needs to be removed from the changelog...

**Comment by ivanperez-keera** [comment]
@alphapapa Is https://github.com/alphapapa/org-ql/pull/395 all that needs to happen?

Have to adjust the PR as needed so that you can merge it (e.g., by mentioning this issue, putting it in my master as opposed to a dedicated branch, etc.).
