### ISSUE TITLE
org-ql-find not working

### ISSUE THREAD

**Issue by arozbiz** [alphapapa/org-ql#338]
`org-ql-find` is not returning anything and throwing an error. E.g., in buffer with the following contents:
```
* TODO heading
```
Running `org-ql-find` and entering "heading" or "todo:" in the prompt returns the error `Wrong type arguments: markerp, nil.` Tracing with edebug, it looks like the problem is the `org-ql-completing-read` function, which returns nil.

**Comment by alphapapa** [comment]
Hello @arozbiz,

Thanks for reporting this problem.  However, I am unable to reproduce it in a clean Emacs configuration on Emacs 28.

**Comment by alphapapa** [comment]
@arozbiz Well, I spent several hours testing it more thoroughly with the default Emacs completion, and I found some issues, including basically what you described.  The "Programmed Completion" API in Emacs is very difficult.  But after much wrangling, this seems to work better now.  Please test with the newest commit on the master branch and let me know if it works for you now.

**Comment by arozbiz** [comment]
It works, thanks.
