### ISSUE TITLE
org-ql-find doesn't work with ivy

### ISSUE THREAD

**Issue by arozbiz** [alphapapa/org-ql#339]
When using ivy (e.g., even a basic install like `(use-package ivy :config (ivy-mode 1))`, `org-ql-find` never returns any matches.

**Comment by neeasade** [comment]
duplicate: see https://github.com/alphapapa/org-ql/issues/284

**Comment by alphapapa** [comment]
Yes, see https://github.com/alphapapa/org-ql/issues/284#issuecomment-1185940983 and following comments.  Thanks @neeasade.
