### ISSUE TITLE
Show efforts for tasks on org-ql-block

### ISSUE THREAD

**Issue by tenpast** [alphapapa/org-ql#342]
Hi Alphapapa, I hope you're doing well!

I would like to show the effort for each task shown in an `org-ql-block`, as is done by N. Rougier in his GTD setup (screenshot attached): https://www.labri.fr/perso/nrougier/GTD/index.html#orgf831e2f.

![2023-03-28-13-30-21-screenshot](https://user-images.githubusercontent.com/43411869/228147993-f847a749-d524-471c-807a-43d43ee4b464.jpg)

This is done using `org-agenda-prefix-format` in his code:

```
(todo "NEXT"
       ((org-agenda-skip-function
       '(org-agenda-skip-entry-if 'deadline))
        (org-agenda-prefix-format "  %i %-12:c [%e] ")
        (org-agenda-overriding-header "\nTasks\n")))
```
        
Can I incorporate the same function in org-ql-block? Or is there a different way to handle this?

Thank you for your help!

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.

This idea is generally covered by this issue: https://github.com/alphapapa/org-ql/issues/262  

See also https://github.com/alphapapa/org-ql/issues/331  It would be easy to add a new "Effort" column here: https://github.com/alphapapa/org-ql/blob/wip/taxy-org-ql-view/taxy-org-ql-view.el#L107

**Comment by alphapapa** [comment]
Correction: See https://github.com/alphapapa/org-ql/issues/23
