### ISSUE TITLE
"Bad timestamp" error while running org-ql-block with "planning" predicate.

### ISSUE THREAD

**Issue by tenpast** [alphapapa/org-ql#343]
I have a recurring TODO which repeats every day, but only Monday through Friday. The way to achieve this was with:

`SCHEDULED: <%%(memq (calendar-day-of-week date) '(1 2 3 4 5))>`

This does what I wanted. However, when adding an org-ql-block with a `(not (planning))` selector, I receive the following error:
```
Bad timestamp '<%%(memq (calendar-day-of-week date) '(1 2 3 4 5))>'
Error was: (not an Org time string: <%%(memq (calendar-day-of-week date) '(1 2 3 4 5))>)
```
And the `org-ql-block` does not get created.

**Comment by alphapapa** [comment]
Hello,

Unfortunately diary sexp timestamps are not yet supported.  Please see https://github.com/alphapapa/org-ql/issues/262
