### ISSUE TITLE
How to sort in the org-ql-block

### ISSUE THREAD

**Issue by Sinthoras7** [alphapapa/org-ql#344]
My goal is to create a custom org-agenda, where only the todo items with a certain tag show up, but they should be sorted by their todo-state (NEXT first, then TODO and WAIT at the bottom).

This code comes close:
```
(setq org-agenda-custom-commands '(
("N" "at home"
         ((org-ql-block '(and (todo "NEXT" "TODO" "WAIT")
                              (tags "@home")
                         )
                        ((org-ql-block-header "what needs to be done at home"))
                        (agenda)
           ))
         )
))
```

But here, the items are not sorted by their state and TODO-items are midst NEXT-items. 
How can I make it sort?

**Comment by alphapapa** [comment]
Please see https://github.com/alphapapa/org-ql/issues/79.
