### ISSUE TITLE
Unable to run usual org functions like refile or schedule on results from org-ql or org-ql-search

### ISSUE THREAD

**Issue by AloisJanicek** [alphapapa/org-ql#35]
I've just noticed that you can't use functions like ~~`org-agenda-refile`~~ or `org-agenda-schedule` on result items when using `org-ql` or `org-ql-search`. I even tried putting `org-ql-block` into `org-agenda-custom-commands` as shown in README, and I got same result.
For example running `org-agenda-schedule` returns _`org-agenda-check-type: No Org agenda currently displayed.`_ 
I kind of understand that org-ql buffers probably aren't usual org-agenda buffers and that org-ql is still in development, so at this point I am just asking if this is an expected behavior or some kind of issue on my side and if former, is there currently any way to use org-ql and be able to manipulate org items directly from results' buffer?

**Comment by mz-pdm** [comment]
This works as a workaround for me:

```
(defun my-set-org-agenda-type (&rest args)
  (when (and (not org-agenda-type)
             (eq major-mode 'org-agenda-mode))
    (set (make-local-variable 'org-agenda-type) 'agenda)))
(advice-add 'org-agenda-schedule :before 'my-set-org-agenda-type)
(advice-add 'org-agenda-deadline :before 'my-set-org-agenda-type)
```

Strangely, simply setting org-agenda-type in the agenda buffer doesn't work, its value remains nil.

**Comment by AloisJanicek** [comment]
Thank you, works perfectly.
I also noticed that today `org-agenda-refile` works for me just fine without advising, strange.

**Comment by alphapapa** [comment]
@AloisJanicek Yes, as noted in the readme:

> Note: The view buffer is currently put in org-agenda-mode, which means that some Org Agenda commands work, such as jumping to entries and changing item priorities (without necessarily updating the view). This feature is experimental and not guaranteed to work correctly with all commands. (It works to the extent it does because the appropriate text properties are placed on each item, imitating an Agenda buffer.)

@mz-pdm Yes, after some quick testing, I also found the `org-agenda-type` variable to be essentially unsettable, even buffer-locally with `setq-local`, which is strange.

I don't know what the best solution is.  I don't think we should be advising functions to work around this in `org-ql`.  Ideally we need to set `org-agenda-type`, then those commands should work.  That's the problem we should try to solve first.

**Comment by mz-pdm** [comment]
The following piece of code, when placed to org-agenda-finalize-hook, makes org-agenda-do-date-later and org-agenda-do-date-earlier (S-right, S-left) commands working:
```el
    (goto-char (point-min))
    (while (not (eobp))
      (let* ((scheduled (org-get-at-bol 'scheduled))
             (pos (and scheduled (plist-get (cadr scheduled) :begin)))
             (marker (org-get-at-bol 'org-marker)))
        (when (and pos marker)
          (move-marker marker pos (marker-buffer marker))))
      (forward-line))
```
Advising the commands with org-agenda-type as outlined above is additionally needed.

**Comment by alphapapa** [comment]
@mz-pdm I don't understand what that code is doing, but we definitely can't be doing anything like that in this package.  We can't advise any `org-agenda` functions here.

**Comment by mz-pdm** [comment]
What the code does is moving org-marker, present in the entry properties, from the beginning of a scheduled entry to its SCHEDULED: date. This is what the org-agenda-do-date-* functions require. It's a workaround I use to make the functions working, which makes my org-ql-block agenda functionality fairly complete.
Of course, we shouldn't advise Org functions, it's just a workaround until a proper solution, setting org-agenda-type, is found (sorry, I don't have time to help with that at the moment).

**Comment by alphapapa** [comment]
Hi Mikhail,

Thank you very much for doing that research, and for sending the PR.  I will see about merging it soon.

**Comment by alphapapa** [comment]
This should be fixed now (at least, for some commands, like scheduling and deadlines).  Thanks to all for your help here.
