### ISSUE TITLE
User-defined sorting signals an error in org-ql-select

### ISSUE THREAD

**Issue by mz-pdm** [alphapapa/org-ql#37]
When I pass a function symbol as `sort' argument to org-ql-select, I get error "SORT must be either nil, or one or a list of the defined sorting methods (see documentation)". I think this is because of the line
  
  (setq sort (-list sort))

that changes the type of `sort' from a function symbol to a list.

**Comment by alphapapa** [comment]
Thanks for reporting that.  It should be fixed now.

It also gave me the idea to add a `random` built-in sorter, which I just did.
