### ISSUE TITLE
Support for timestamps with internal time ranges (events)

### ISSUE THREAD

**Issue by hpfr** [alphapapa/org-ql#371]
Org QL does not currently match timestamps with internal time ranges, commonly used for events. These are different from time/date ranges where two timestamps are connected by `--`.

The example from the [manual](https://orgmode.org/manual/Timestamps.html):
```
* Discussion on climate change
  <2006-11-02 Thu 20:00-22:00>
```

Interestingly, the latest [Org Syntax](https://orgmode.org/worg/org-syntax.html#Timestamps) document just defines times as:

> TIME (optional)
>     An instance of the pattern H:MMREST where H represents a one to two digit number (and can start with 0), and M represents a single digit. REST can contain anything but \n or closing bracket.

I was wondering if the Org QL behavior was by design or simply because you don’t personally use these. I think this could be fixed by changing the timestamp regexp, but the predicate code is pretty complex, so I don’t know the full implications of that.

Somewhat related to https://github.com/alphapapa/org-ql/issues/159

---

Matching these timestamps would be another step towards fully replacing the Org agenda with Org QL (and its caching!). There is currently no mechanism for generating an Org agenda-like time grid, but I think it makes sense for Org QL to limit its scope to simply returning (and in the case of `org-ql-view`, displaying) lists of headings. Matching timestamps with internal time ranges would mean a package like [`calfw`](https://github.com/haji-ali/emacs-calfw) could leverage a `calfw-org-ql` backend rather than the `org-agenda`-based [`calfw-org`](https://github.com/haji-ali/emacs-calfw/blob/7302a966f393c3249f4c27070232e90aee04fef1/calfw-org.el#L90-L105).

**Comment by alphapapa** [comment]
This is a nicely written bug report, but please see #237, which it duplicates.

**Comment by hpfr** [comment]
I must have only searched issues. Well, now there is an issue that PR can close :sweat_smile:

**Comment by alphapapa** [comment]
Yeah, probably good to have this as an issue, and since you wrote it up so well, might as well use this one.  :)

**Comment by alphapapa** [comment]
v0.8.7 will allow such ranges to be matched simply, but matching depending on the specific inner time ranges will not work yet.  That will require some refactoring, and so it will be done in a future version (maybe v0.9, maybe not).
