### ISSUE TITLE
Org-ql + doom emacs issues

### ISSUE THREAD

**Issue by kunalomizer** [alphapapa/org-ql#375]
Using Doom Emacs. My modifications basically include
Adding packages to packages.el and
I have defined my org directory in config.el
I have defined custom todo keywords in config.el

additionally I have created functions within my config.el to create org-ql queries which are relatively straight forward - basically sorting the above defined custom keywords in a view.
Configurations:
GNU Emacs v29.1 nil
Doom core v3.0.0-pre HEAD -> master 844a82c4 2023-09-22 23:18:31 +0200
Doom modules v23.09.0-pre HEAD -> master 844a82c4 2023-09-22 23:18:31 +0200

This whole setup was working wonderfully till about 2 weeks ago when I am not if I modified something by mistake or if it was because I ran doom upgrade.

Now every time I try to call the function, I get : Error running timer ‘org-reveal’: (error "‘org-element-at-point’ cannot be used in non-Org buffer #<buffer *doom*> (+doom-dashboard-mode)") [19 times]

I have nuked my doom directory and reinstalled, yet I still get the same error. I furthermore tried starting emacs with "emacs -Q" and then inserting ":org-mode" but that also gives me the same error. Is this a bug?

**Comment by alphapapa** [comment]
Please see https://github.com/alphapapa/org-ql/issues/364
