### ISSUE TITLE
How to search for regular expressions, as opposed to strings, in helm-org-ql

### ISSUE THREAD

**Issue by bobf32** [alphapapa/org-ql#376]
E.g. \<foo\> to search for ```foo``` in ```foo bar``` but not ```foobar``` doesn't seem to work. I can only seem to find strings, not regexps.

**Comment by alphapapa** [comment]
Hello @bobf32,

Have you looked at the list of predicates in the documentation?  Some of them support regexps.

**Comment by bobf32** [comment]
I have indeed, and can see how it's done using sexp syntax, but helm-org-ql does not support this. It's not clear to me from the examples I've seen how it would be done using non-sexp syntax.

**Comment by alphapapa** [comment]
Well, maybe there are edge cases, but typing this into the prompt seems to work for me: `heading-regexp:"T.ke"` which matches a heading like `Take over the world`.

**Comment by bobf32** [comment]
Error: insufficient user iq. I see it now: regexp:"\<foo\>" ftw. Thanks for bearing with me.

**Comment by alphapapa** [comment]
You're welcome.
