### ISSUE TITLE
Views not saved persistently

### ISSUE THREAD

**Issue by Pentaquark1** [alphapapa/org-ql#378]
Hi,

when I save an org-ql-search, it will show up in helm-org-ql-views and all the other related functions that show saved views.
However after restarting emacs, only the default views show up.

Using latest doom emacs, org-mode 9.7, Gnu Emacs 29.1

BR

**Comment by alphapapa** [comment]
Hello,

Please try to reproduce the problem in a clean Emacs configuration, e.g. using https://github.com/alphapapa/with-emacs.sh

**Comment by Pentaquark1** [comment]
Hi,
let me know if I did this right:
- cloned that repo, then ran it with `./with-emacs.sh -i org-ql --dir ~/new-emacs.d`
- then created some random view, saved the view. checked with `org-ql-view` that it shows up, it does
- closed emacs, then ran it with the exact same cmd as above again, checked `org-ql-view`, my random view is not there anymore

That tip with Emacs bookmarks is a nice. I checked my bookmark and there was a burly bookmark of a view that I apparently made while tinkering and forgot about. That might serve just fine as well

**Comment by alphapapa** [comment]
Thanks.  I can confirm the bug now.  Something must have changed in recent Emacs versions.  Should be a simple fix.

**Comment by alphapapa** [comment]
@Pentaquark1 I think that will fix it.  Would you please install from this branch and let me know if it works for you?  https://github.com/alphapapa/org-ql/tree/stable/0.7

**Comment by alphapapa** [comment]
Seems to work for me.
