### ISSUE TITLE
Wrong `regexp' predicate documentation

### ISSUE THREAD

**Issue by mz-pdm** [alphapapa/org-ql#39]
The documentation says:
```
regexp (regexp)
    Return non-nil if current entry matches REGEXP (a regexp string).
```
However, an rx expression is expected, not a string. A string may be provided but then it's escaped rather than interpreted as a regexp.

**Comment by mz-pdm** [comment]
It's also not very clear what the regexp is matched against. It seems to be the whole entry, included properties etc., it would be nice to have it documented.

**Comment by alphapapa** [comment]
Thanks for pointing those out.  They should be fixed now.
