### ISSUE TITLE
org-ql-block in agenda doesn't return any results

### ISSUE THREAD

**Issue by max6166** [alphapapa/org-ql#391]
### Discussed in https://github.com/alphapapa/org-ql/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **max6166** December 30, 2023</sup>
I've been trying to get something very similar to the [org-ql-block](https://github.com/alphapapa/org-ql#function-org-ql-block) example in the docs to work. 

The agenda created with regular search terms populates correctly.
But the `org-ql-block` version doesn't return any results. It only displays the header string and is otherwise empty.

After 2 days of trying to figure out the problem, I'm still stumped. Any help would be greatly appreciated. 

```
(setq org-agenda-custom-commands
  '(("v" "org-ql: home 2DAY"
      ((org-ql-block '(and (todo "2DAY")
                        (tags "home"))
         ((org-ql-block-header "org-ql: 2DAY o1")))))
     ("V" "search: home 2DAY"
       ((tags-todo "+home/!2DAY")))))
```
</div>

**Comment by alphapapa** [comment]
Please don't report a problem in two places at the same time.  It's unlikely that there's a bug here, so the discussion should be enough.

**Comment by max6166** [comment]
Sorry. After I posted in the discussion area, I clicked yes on the prompt to make my post an issue. I am very suggestible.
