### ISSUE TITLE
Document integration with org-super-agenda

### ISSUE THREAD

**Issue by mwfogleman** [alphapapa/org-ql#4]
In the README, you show org-super-agenda as a way to visually demonstrate the groupings. Can you explain how to do that in the README or elsewhere?

**Comment by alphapapa** [comment]
All you need to do is install and configure org-super-agenda according to
its own instructions. There's nothing special to do for this package.

**Comment by alphapapa** [comment]
Please let me know if you need any help with org-super-agenda.  I'll be adding more documentation here before submitting to MELPA.

**Comment by alphapapa** [comment]
This is in the readme now.  Thanks.
