### ISSUE TITLE
org-ql-block "Query:" headers sometimes not put on a new line

### ISSUE THREAD

**Issue by mz-pdm** [alphapapa/org-ql#40]
"Query:" headers are sometimes attached to the preceding line rather than put on the next line, when using multiple org-ql-block entries in a single agenda. For example:
```
Query:(todo "FEEDBACK")  In:("~/org/...")
  FEEDBACK [#B] xxx
  FEEDBACK yyy Query:(todo "TODO")  In:("~/org/...")
  TODO [#A] zzz
```

**Comment by alphapapa** [comment]
Thanks for reporting this.  I think that should fix it, but please let me know if more changes are needed.

**Comment by mz-pdm** [comment]
It looks fine, thank you.
