### ISSUE TITLE
When use-package, why do I get "package-compute-transaction: Package ‘compat’ (version 29.1.4.1) is unavailable"?

### ISSUE THREAD

**Issue by madorian** [alphapapa/org-ql#403]
### OS/platform

NixOS GNU/Linux

### Emacs version and provenance

GNU Emacs 29.2 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)

### Emacs command

emacs

### Org version and provenance

Org mode version 9.7-pre (release_9.6.7-544-g2e2ed4 @ /home/b0ef/.emacs.d/straight/build/org/)

### org-ql package version and provenance

use-package

### Actions taken

I probably grabbed git of emacs

### Observed results

it didn't work

### Expected results

to work

**Comment by alphapapa** [comment]
Why do you think this is a bug in org-ql?  You're using straight.el.  Why don't you ask them about this problem?
