### ISSUE TITLE
void-variable org-ql-view-dispatch

### ISSUE THREAD

**Issue by wztdream** [alphapapa/org-ql#418]
### OS/platform

ubuntu 20.04

### Emacs version and provenance

29.2

### Emacs command

org-ql-search

### Org version and provenance

Org mode version 9.6.15 (release_9.6.15 @ /snap/emacs/current/usr/share/emacs/29.2/lisp/org/)

### org-ql package version and provenance

org-ql-20210901.175458

### Actions taken

open any org file, then run `org-ql-search`

### Observed results

show below message and nothing happens then.
Symbol’s value as variable is void: org-ql-view-dispatch

### Expected results

It should begin to search right?

### Backtrace

```elisp
Debugger entered--Lisp error: (void-variable org-ql-view-dispatch)
  byte-code("\301\302\303\304\303\305%\210\306\10\303\307\310\311%\207" [org-ql-view-dispatch cl-generic-define-method transient-infix-set nil ((obj org-ql-view--variable) value) #f(compiled-function (obj value) "Set Org QL View variable defined by OBJ to VALUE." #<bytecode 0x7b52cac1af2bf38>) define-transient-command "Show Org QL View dispatcher." [["Edit" ("t" org-ql-view--transient-title) ("q" org-ql-view--transient-query) ("i" org-ql-view--transient-in) ("s" org-ql-view--transient-sort) ("g" org-ql-view--transient-super-groups)]] [["View" ("r" "Refresh" org-ql-view-refresh) ("v" "Select" org-ql-view)] ["" ("C-s" "Save" org-ql-view-save) ("C-k" "Delete" org-ql-view-delete)]]] 6)
  #<subr require>(org-ql-view)
  apply(#<subr require> org-ql-view)
  require(org-ql-view)
  load-with-code-conversion("/home/wangzongtao/.emacs.d/elpa/29.2/develop/org-q..." "/home/wangzongtao/.emacs.d/elpa/29.2/develop/org-q..." nil t)
  command-execute(org-ql-search)
```

### Etc.

I did some debug, it seems this is caused by mismatch of `transient` package.
It seems you use `define-transient-command` to define o`rg-ql-view-dispatch`, but there is no such command in `transient` package now, and the transient package I use is the new with version: 20240227.73232. Maybe trasient has removed this command? I am not sure.

```elisp
(define-transient-command org-ql-view-dispatch ()
  "Show Org QL View dispatcher."
  [["Edit"
    ("t" org-ql-view--transient-title)
    ("q" org-ql-view--transient-query)
    ("i" org-ql-view--transient-in)
    ("s" org-ql-view--transient-sort)
    ("g" org-ql-view--transient-super-groups)]]
  [["View"
    ("r" "Refresh" org-ql-view-refresh)
    ("v" "Select" org-ql-view)]
   [""
    ("C-s" "Save" org-ql-view-save)
    ("C-k" "Delete" org-ql-view-delete)]])
```

**Comment by alphapapa** [comment]
Well:

> org-ql package version and provenance

> org-ql-20210901.175458

Current date: 2024-03-06

Relevant commit: https://github.com/alphapapa/org-ql/commit/847f3994caab28ea38323d2e5bcbe4ca5cf7c301
Dated: Mar 18, 2022
