### ISSUE TITLE
Dynamicblocks across multiple files

### ISSUE THREAD

**Issue by Gavinok** [alphapapa/org-ql#421]
### OS/platform

linux

### Emacs version and provenance

29.3

### Org version and provenance

9.6.15

### org-ql package version and provenance

0.9-pre

### Description

I would like to have a version of dynamic blocks that let me search across multiple files and directories to create a table. The inspiration for this was https://github.com/blacksmithgu/obsidian-dataview which has a similar query language and is used to generate a table but instead of just using the current note it uses all of your notes at once.

**Comment by alphapapa** [comment]
Please see #151.
