### ISSUE TITLE
Refreshing after a query fails

### ISSUE THREAD

**Issue by jwiegley** [alphapapa/org-ql#475]
### OS/platform

macOS

### Emacs version and provenance

29.4 macport build via Nix

### Emacs command

emacs

### Org version and provenance

9.7.13, pulled from Org releases and built with Nix

### org-ql package version and provenance

0.9-pre, from nixpkgs

### Actions taken

Use this function to perform a query, which works:
```
(defun org-config-show-filetagged-tasks (tag)
  "Report items pending review after one second."
  (interactive "sTag: ")
  (org-ql-search (org-agenda-files)
    '(and (todo)
          (save-excursion
            (goto-char (point-min))
            (re-search-forward (concat "#\\+filetags:.*:" tag ":") 4096 t)))
    :sort '(scheduled todo)))
```
Then, hit `g` to refresh the results buffer.

### Observed results

I get this error:
```
byte-compile-log-warning: Invalid Org QL query: "Invalid Org QL query: \"reference to free variable ‘tag’\", :warning", :error
```

### Expected results

I expected it to refresh the buffer.

### Backtrace

```elisp
Interestingly enough, `debug-on-error` does not catch this error.
```

**Comment by alphapapa** [comment]
Hi John,

I think this is because the query sexp is internally byte-compiled in a lambda, but not as a closure, so it doesn't capture the value of `tag` in the outer function.  I think to fix it you just need to backquote the query sexp and unquote that variable, so its value gets inlined.

**Comment by jwiegley** [comment]
ah! that makes so much sense

**Comment by alphapapa** [comment]
Also, I think you could test for that filetag in a way that would be a bit more robust and likely friendly to caching...let me see...

**Comment by jwiegley** [comment]
Yes, that fixed it, thank you so much.

**Comment by alphapapa** [comment]
This seems to work:

```el
(org-ql--value-at
 (point-min) (lambda ()
               (org-entry-get nil "filetags" t)))
```
`org-ql--value-at` caches per buffer, as long as the buffer isn't modified.  And `org-entry-get` gets the entry from a document-level `:PROPERTIES:` drawer.  But it does *not* get it from the `#+filetags:` header, so you would need to switch from `#+filetags:` to
```org
:PROPERTIES:
:filetags: 
:END:
```
But there should also be a function that works with the `#+` headers...

**Comment by alphapapa** [comment]
The keywords are in the variable `org-options-keywords`, but the only function I can find is in `org-export`, which you might not want to use.  Anyway, hope this helps somehow.

**Comment by jwiegley** [comment]
I definitely don't want to define these properties at the entry level, but only in the `#+filetags`...

**Comment by alphapapa** [comment]
> I definitely don't want to define these properties at the entry level, but only in the `#+filetags`...

I mean in a document-level properties drawer, not within an entry.  Those are still relatively new in Org, so maybe you didn't notice the feature yet.  :)  (Though I'm only guessing that setting that property in the document-level drawer has the same effect...)

**Comment by jwiegley** [comment]
Ah, I see. Actually, I currently use BOTH file properties (for file-level `ID`), and `#+filetags`, etc. It's nice in a ways because the title and filetags aren't hidden from view due to their being in a property drawer...
