### ISSUE TITLE
Argument handling in org-agenda-ql

### ISSUE THREAD

**Issue by natrys** [alphapapa/org-ql#5]
Hi, I probably shouldn't be using the issue tracker to bother you with something as small as this. But this example in the README doesn't work:

``` elisp
(org-ql-agenda "~/org-super-agenda/test/test.org"
  (and (or (date = today)
           (deadline <=)
           (scheduled <= today))
       (not (done))))
```

This particular example incidentally errors with a `(void-variable todo-keyword)` but right now I don't mean this. 

The form: `(org-ql-agenda "~/path/to/file" query)` in general doesn't work unless a keyword argument is provided in the end (such as :sort nil). This seems to be a shortcoming in the `pcase` based argument matching in `org-ql-agenda` macro. I had to add another case handling condition to make it work:

        (`(,arg-files ,arg-pred)
         (setq files arg-files
               query arg-pred))

But you may have some other cleaner means in mind.

**Comment by alphapapa** [comment]
Thanks, I made some changes to that code recently but didn't test all the combinations that are possible.  (I wish there were a more flexible way to handle arguments, but I haven't come up with anything suitable yet.  If you are interested in this, take a look at https://github.com/magnars/dash.el/issues/268.)

> This particular example incidentally errors with a (void-variable todo-keyword) but right now I don't mean this.

Not sure why that would happen, as I just tested the example and it works for me.  Please let me know if it still happens, as it's probably a bug that needs fixing.

**Comment by alphapapa** [comment]
Actually, I think I found and fixed that bug.  Thanks for reporting it!  My config made it unnoticeable for me.

**Comment by natrys** [comment]
Thanks for the quick fix. Next up, when I run the example again, it now shows: `(void-variable repeat)` when it hits [this line](https://github.com/alphapapa/org-ql/blob/d3cb2bfeed1dc5bd91e8a55993cb136426aae045/org-ql-agenda.el#L292).

I don't really understand what's going on here, perhaps you wanted to mean `repeat-day-number`? Also, here it seems nothing happens when this condition is satisfied. But then `prefix` becomes `t`, is that desired?

**Comment by alphapapa** [comment]
Sorry, that was leftover code that wasn't being exercised in my config.  I removed it, so it should be fixed.  Thanks.
