### ISSUE TITLE
could you add an additional newline to the end of the buffer that org-ql creates for a search?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-ql#50]
I work on small resolution screens sometimes, If I navigate to the end of an org-ql search buffer, if the headline has a tag, it scrolls the buffer all the way to the right (as the tag is right aligned on the heading). 

If it's possible to have a newline added to the end of each buffer that would prevent the horizontal scroll when I navigate to the end of it.

**Comment by alphapapa** [comment]
Great idea, thanks.
