### ISSUE TITLE
is it possible to add an arbitrary title (with custom face) in an org-ql search buffer?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-ql#51]
The existing `:title` attribute changes the title in the small band at the top, but I wanted my agenda to actually have a custom title that I could set the face for (want to make it a bit bigger + have it show today's date for e.g.)

**Comment by xeijin** [comment]
And ideally hide the original 'title' bar & query 

My use-case here is creating a 'dashboard' which is composed of multiple windows each with their own org-ql query, just want to make it look a little cleaner

**Comment by alphapapa** [comment]
It's a little hard for me to understand exactly what you're asking for, because you're not using the technical terms that Emacs uses for UI elements.  :)  For example, the "small band at the top" is the buffer's header line.

The dashboard thing sounds interesting, but I don't understand why you'd want to turn off the header lines in each buffer, because those would be the best way to display that information.  If you want to change the face of the title in the header line, that would be simple: just use the `propertize` function to set the `face` property of the string you're using as the header.

BTW, you might find the `yequake` package helpful.  I have an Org frame that I have bound in my desktop environment to Super+O, which toggles this frame on and off.  Every time it opens it displays the same buffers in the same places, so it's much like an Org dashboard for me.

![yequake-org](https://user-images.githubusercontent.com/601365/68249903-5890f780-ffe5-11e9-8d88-d9b03dd279f2.png)

```el
(use-package yequake
  :quelpa (yequake :fetcher github :repo "alphapapa/yequake")
  :custom
  (yequake-frames
   (list
    (cons "Org"
          (list
           (cons 'buffer-fns
                 '("~/org/temp.org" split-window-horizontally
                   (lambda nil
                     (or (get-buffer "*Org Agenda*")
                         (save-excursion
                           (ap/org-agenda-list)
                           (current-buffer))))
                   (lambda nil
                     (org-sidebar :buffers
                                  (list (org-now-buffer)
                                        (org-ql-view--list-buffer))
                                  :fns
                                  (list (lambda
                                          (&rest _ignore)
                                          (make-org-sidebar :name "Today or NEXT"
                                                            :items
                                                            (org-ql-select
                                                              (org-agenda-files)
                                                              '(or (ts-active :on today)
                                                                   (todo "NEXT"))
                                                              :sort '(deadline scheduled priority todo)
                                                              :action 'element-with-markers)
                                                            :super-groups
                                                            '((:name "Today" :time-grid t :deadline today :scheduled today)
                                                              (:priority "A")
                                                              (:name "Dated" :deadline t :scheduled t)
                                                              (:name "Undated" :anything t)))))))
                   (lambda nil
                     (with-selected-window (get-buffer-window (org-ql-view--list-buffer))
                       (setf (window-height) (1+ (line-number-at-pos (point-max))))
                       (goto-char (point-min))))
                   (lambda nil
                     (select-window
                      (get-buffer-window
                       (find-buffer-visiting "~/org/temp.org"))))))
           (cons 'width 0.95)
           (cons 'height 0.9)
           (cons 'alpha 0.95)
           (cons 'frame-parameters
                 (list
                  (cons 'undecorated t)
                  (cons 'skip-taskbar t)
                  (cons 'sticky t))))))))
```

**Comment by xeijin** [comment]
firstly let me say `yequake` is awesome, and is exactly how I plan to implement a 'globally summonable agenda' alongside autohotkey on windows, once I get my agenda views built!

The screenshot below probably explains what I want to do better, I also dont have any need to see the query, just a title, hence I thought disabling the buffer header might be the way to go.

![image](https://user-images.githubusercontent.com/291385/68349897-9a5d9300-00f6-11ea-928a-6d50ba578287.png)

Aside from a general title, I also want to add arbitrary text to the buffer from other functions I have in my config (e.g. I use projectile to manage non-development 'project' work -- I initialise a project as a git repo and at the end of every day I commit the days work with a brief summary of where the project currently sits - I want to bring this commit message into my agenda 'dashboard' as an example)

**Comment by alphapapa** [comment]
Cool, I like the font in those headers!  What is that?

Inserting arbitrary text into the buffer is probably not a great idea, to be honest, because it's likely to cause issues one way or another, probably in unforeseen ways.  It's an `org-agenda-mode`  buffer, which implies certain expectations of its content.  

But if you know what you're doing, you can do so in your own code rather than by modifying `org-ql-view` functions.  Or you could copy the content into your own dashboard buffers, but that might mean defining your own major mode and dealing with interactive commands yourself.

Another alternative, and likely the best one, would be to use overlays to display extra information in the buffers.  You can insert and clear them in your own code which would call the `org-ql` functions.

You may also find some interesting ideas about dashboards here: https://github.com/akirak/corefighter.el

**Comment by xeijin** [comment]
@alphapapa  the font is **[Major Mono Display](https://fonts.google.com/specimen/Major+Mono+Display)** from google fonts

Thanks for the overview (and corefighter.el, looks interesting). Your points make sense. I do indeed want to continue using interactive commands (especially `bulk (B)`. 

I think you may have touched on it, but one thing I want to explore before I go down the fully custom / overlays route: 

I notice that when point is on newlines (and I guess by implication, any line that isnt a group heading or org heading) the keymap is different (e.g. I can use my evil keybinds to navigate without triggering the interactive agenda functions). Therefore, would it not be possible to inject strings above/below the new-lines, with the agenda parts remaining unaffected?

It would be great to then have a new plist keyword like `:customheader` that accepted a function which outputs a string. I'd be happy to work on a PR if you don't think this approach will cause any issues.

**Comment by alphapapa** [comment]
> Therefore, would it not be possible to inject strings above/below the new-lines, with the agenda parts remaining unaffected?

Maybe; you'd have to look at the relevant code (e.g. bulk actions code) to determine how it finds items to act on.  The spec is the code, and it probably wasn't intended to be used like that.

> It would be great to then have a new plist keyword like :customheader that accepted a function which outputs a string. One could then insert it above / below a super-group to even break an agenda down into sections. I'd be happy to work on a PR if you don't think this approach will cause any issues.

I appreciate the offer, but that feels out-of-scope to me, so I'd probably decline it.  But please feel free to open an issue on the `org-super-agenda` repo where we could discuss it in more detail.  Maybe we could define the feature more concretely and work something out, or at least figure out a way to customize the behavior in your own config.

**Comment by xeijin** [comment]
Will have a go at figuring this out for my own config & will definitely open an issue in org-super-agenda if I get stuck, thanks for the offer of help!

**Comment by xeijin** [comment]
@alphapapa, moving discussion back to this ticket.

I wrote the following function to advise `org-ql-view--header-line-format`, stripping out what I don't need from the original buffer `header-line`:

```lisp
(defun +xeijin/org-ql-header (buffers-files query &optional title)
"Return customised header-line-format for BUFFERS-FILES and QUERY.
  Intended as a replacement the function `org-ql-view--header-line-format'."

  (let* ((title (if title
                    (concat (propertize "" 'face 'org-agenda-structure)
                            title " ")
                  "")))
    title))
```

I'm then using it in the following wrapper function for `org-ql-search`:

```lisp
(defun +xeijin/org-ql-search (&rest args)
  "Customise `org-ql-search' with a re-defined header-line and heading faces."

  (let ()
    (unwind-protect
        (progn
          (advice-add 'org-ql-view--header-line-format :override #'+xeijin/org-ql-header)
          (apply #'org-ql-search args)
          (advice-remove 'org-ql-view--header-line-format #'+xeijin/org-ql-header))

      (advice-remove 'org-ql-view--header-line-format #'+xeijin/org-ql-header))))
```

This works fine but as soon as I refresh with `org-ql-view-refresh` it reverses my changes.

I guess this means I need to advise `org-ql-view-refresh` too, but before I do, is there a cleaner way to do this?

I know I could simply overwrite the defun for `org-ql-view--header-line-format`, but I do like to keep the usual header-line details when I'm executing ad-hoc queries.

**Comment by alphapapa** [comment]
The way you're using advice doesn't seem idiomatic.  Why don't you use `:around` advice for `org-ql-view--header-line-format`?

**Comment by xeijin** [comment]
> The way you're using advice doesn't seem idiomatic. Why don't you use `:around` advice for `org-ql-view--header-line-format`?

@alphapapa OK, I've cleaned things up:

define/set faces:

```lisp
(defface +xeijin/org-agenda-header-line
    '((t :height 200
         :font "Major Mono Display 32"
         :inherit header-line))
    "custom face for the header-line in `org-ql-search' buffers")

(set-face-attribute 'org-super-agenda-header nil
                    :font "Major Mono Display 20"
                    :overline t)
```

wrapper function which will advise `org-ql-view--header-line-format` using `:around`:

```lisp
(defun +xeijin/org-ql-view--header-line-format (orig-fn &rest args)

  (let ((title (nth 2 args)))

   ; check there is a title, check the init var is bound, check it's true
   (if (and (stringp title) (boundp 'org-ql-custom-header) org-ql-custom-header)

       ; return custom header
       (propertize title 'face "+xeijin/org-agenda-header-line")

    ; no custom header
    (apply orig-fn args))))
```

However as mentioned, I still want to preserve the original header-line, hence the advice is driven based on the variable `org-ql-custom-header` being `t`, given this limitation presumably I'll need to create a wrapper function for `org-ql-view-refresh` too?

**Comment by alphapapa** [comment]
That looks much more idiomatic.  :)

One more suggestion, though: name your advice function exactly like the one it's replacing, but with your custom prefix, because that will make its purpose more obvious.

> However as mentioned, I still want to preserve the original header-line, hence the advice is driven based on the variable org-ql-custom-header being t, 

I'm not aware of an `org-ql-custom-header` variable.  I doubt you would need such a variable to implement this, anyway.  

> given this limitation presumably I'll need to create a wrapper function for org-ql-view-refresh too?

I don't think so.  You can see in `org-ql-search` that `org-ql-view--header-line-format` is called every time, and `org-ql-view-refresh` calls `org-ql-search`.  Did you try your code?

**Comment by xeijin** [comment]
> That looks much more idiomatic. :)
> 
> One more suggestion, though: name your advice function exactly like the one it's replacing, but with your custom prefix, because that will make its purpose more obvious.
> 
> > However as mentioned, I still want to preserve the original header-line, hence the advice is driven based on the variable org-ql-custom-header being t,
> 
> I'm not aware of an `org-ql-custom-header` variable. I doubt you would need such a variable to implement this, anyway.
> 
> > given this limitation presumably I'll need to create a wrapper function for org-ql-view-refresh too?
> 
> I don't think so. You can see in `org-ql-search` that `org-ql-view--header-line-format` is called every time, and `org-ql-view-refresh` calls `org-ql-search`. Did you try your code?

Ah I see what you mean now, if I run ad-hoc queries (where I won't specify titles anyway) then my custom propertize statement never kicks-in, makes sense, thank you! Updated the code in my earlier post to reflect this.
