### ISSUE TITLE
orq-ql--value-at - misbehave

### ISSUE THREAD

**Issue by hubisan** [alphapapa/org-ql#59]
Starting with a simple org file:

```text
* first
* second
```

Calling 
```emacs-lisp
(org-ql--value-at 1 #'org-get-heading)
```

on first heading gives me `first` as expected.

Then deleting first two lines to move second heading to where first heading was and calling:

```emacs-lisp
(org-ql--value-at 1 #'point)
(org-ql--value-at 1 #'org-get-heading)
```
Returns `first` instead of the expected `second`.

This is most certainly due to not setting `value-cache` to `nil` in `org-ql--value-at` when cache is invalid. And then using `(map-put value-cache fn new-value)` on the `value-cache` which still includes other fn than `point`, `org-get-local` in this case. So this adds the position value cache with the new modified tick including other fn than the current one.

Or maybe it's just too late ... :beer:

**Comment by alphapapa** [comment]
Hi Daniel,

Great catch.  Thank you for your clear report.  This should fix it.
