### ISSUE TITLE
invalid function helm-build-sync-source

### ISSUE THREAD

**Issue by matthuszagh** [alphapapa/org-ql#60]
I'm getting the error shown in the title when calling `helm-org-ql`. This seems to be similar to [an issue reported for dumb-jump](https://github.com/jacktasia/dumb-jump/issues/224). I don't get this issue if I uncomment the helm requires:

```elisp
;; (require 'helm)
;; (require 'helm-org)
```

I'm using emacs 27.05.

**Comment by alphapapa** [comment]
I'm confused: I pointed you to this package from the discussion on the Helm repo.  Do you not already have Helm installed and loaded?

Anyway, as noted in that issue, the macro call should probably be replaced with the expansion to call `helm-make-source` directly.

**Comment by alphapapa** [comment]
That should fix it.  Thanks.

**Comment by matthuszagh** [comment]
Helm needs to be available when it’s byte compiled. This can be an issue for systems like Nix (which I use).

**Comment by alphapapa** [comment]
That explains it.  :)  Yeah, Nix and Guix are doing some really interesting things in their packaging, but issues like this are bound to happen with it, because I don't think anyone is developing these Emacs packages with such systems in mind.
