### ISSUE TITLE
Changes to heading and regexp predicates

### ISSUE THREAD

**Issue by tumashu** [alphapapa/org-ql#64]
```
                                ;; Heading text.
                                ;; MAYBE: Adjust regexp to avoid matching in tag list.
                                (`(heading ,regexp)
                                 ;; Only one regexp: match with preamble, then let predicate confirm (because
                                 ;; the match could be in e.g. the tags rather than the heading text).
                                 (setq org-ql-preamble (rx-to-string `(seq bol (1+ "*") (1+ blank) (0+ nonl)
                                                                           ,regexp)
                                                                     'no-group))
                                 element)

```

```
(rx-to-string `(seq bol (1+ "*") (1+ blank) (0+ nonl)
                    "[a][b]"))

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/70370280-5ed60480-1900-11ea-9856-56db85eaa2ca.png)

**Comment by alphapapa** [comment]
?

**Comment by tumashu** [comment]
If I have a  headline  * aaabbb， I can not search with query “heading;[a]+[b]+”

**Comment by tumashu** [comment]
for it will become  

"\\\\(?:^\\\\*+[[:blank:]]+.*\\\\[a]\\\\+\\\\[b]\\\\+\\\\)"

instead of

"\\\\(?:^\\\\*+[[:blank:]]+.*[a]+[b]+\\\\)"

**Comment by tumashu** [comment]
maybe the below?
```
(rx-to-string `(seq bol (1+ "*") (1+ blank) (0+ nonl)
                    ,(xr "[ab]+[bc]+")))

``

**Comment by alphapapa** [comment]
As mentioned on #66, I'd prefer to handle this issue another way.

FYI, note that `rx` has a `regexp` form for inserting strings as regexps; you don't need to use `xr` for that (as cool as `xr` is).

**Comment by alphapapa** [comment]
Copying my plans from #66:

> 1.  Change the `heading` predicate to search for a plain-text string rather than a regexp.  That's probably a good idea anyway, because users might want to search for headings containing regexp metacharacters, which is difficult if they're treated as such.
> 2.  Consider making a new `heading-regexp` predicate to search for actual regexps in headings.  However, the existing `regexp` predicate might be sufficient.
> 3.  Consider also making a new "entry" predicate which would search entry text as plain-text rather than as a regexp, and consider making it the default predicate.  Regexp searches make more sense in the Lisp syntax, but in the non-Lisp syntax, having regexp be the default is probably not best, because users ought to be able to search for, e.g. strings containing parens, question marks, etc.
> 4.  The default predicate should probably be specified as a `defvar` or `defcustom`, which could be bound in custom commands around calls to `org-ql` functions.  That's generally more flexible and avoids the need to rewrite code to pass arguments through chains of function calls.
> 5.  The `r` alias for the `regexp` predicate is a good idea!

**Comment by wztdream** [comment]
@alphapapa 
Hi, I think searching heading with regexp is useful. 

Follow your conversation,  it seems to me if we change the heading predicate without regexps, i.e. `(heading)` to check where it is a heading,  that will solve the issue. 

We can use `(and (heading) (regexp "some-search-pattern")` to use regexp search only in heading.

**Comment by alphapapa** [comment]
@wztdream That's an interesting idea, but I don't think it will work.  The `regexp` predicate searches the entire entry, not just the heading.
