### ISSUE TITLE
Package.el Library header

### ISSUE THREAD

**Issue by chrisbarrett** [alphapapa/org-ql#7]
This package looks pretty cool! I'm gonna have a play with it. 😻

Skimming the sources, I note that you're depending on dash.el, but your main file lacks the metadata package.el parses to install dependencies. You might like to have a skim of the Emacs documentation on [Library headers](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html), and adapt the headers from another package, e.g. [flycheck](https://github.com/flycheck/flycheck/blob/master/flycheck.el). Sorting the headers out is a prerequisite for getting your code on MELPA down the track. :)

You might also consider using seq.el to remove the dependency on dash, though I'm sure there's some work there. There's something to be said for sticking with the stuff shipped with Emacs out-of-the-box. :)

**Comment by alphapapa** [comment]
Hi Chris,

Well, I have a few packages on MELPA already, so I'll be cleaning things up before I submit this package, but thanks for the reminder.  ;)

**Comment by alphapapa** [comment]
FYI, org-ql is on MELPA now.
