### ISSUE TITLE
org-ql-search buffers are not read-only

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-ql#72]
Not sure if this is a bug, but `org-ql-search` buffers do not appear to be read-only like regular agenda buffers, specifically `backward-kill-word` results in me being able to delete a buffer (tested this with `emacs --q` to make sure it wasnt something in my config)

**Comment by alphapapa** [comment]
Good catch.  I thought that was covered by `org-agenda-mode`, but apparently not.  Thanks.
