### ISSUE TITLE
predicate for effort?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-ql#80]
I know `org-super-agenda` has `:effort<` and `:effort>` but that forces me to use grouping in the agenda, would it be possible to get a predicate for `org-ql`?

I'm guessing I could also do this manually with the `property` predicate, but as the effort is a string I havent quite managed to figure out how to do the comparison....

```emacs-lisp
(org-ql-block '(and (todo) (property "Effort" (< 5 (string-to-number "5")))))
```

**Comment by alphapapa** [comment]
You need to pass a lambda to compare the value, not a sexp.

**Comment by xeijin** [comment]
Thanks, I guess this also works, adapted from one of the other examples:

```emacs-lisp
(org-ql-block '(and (todo)
                                (property "Effort")
                                (<= 5 (string-to-number (org-entry-get (point) "Effort"))))
                          ((org-ql-block-header "  < 25 mins\n"))))
```

**Comment by xeijin** [comment]
actually, @alphapapa I was expecting this to work and it doesn't, could you tell me where I'm going wrong?

```emacs-lisp
            (org-ql-block '(and (todo)
                                (property "Effort" (lambda (e) (<= 5 (string-to-number e))
                                          ;;(<= 5 (string-to-number (org-entry-get (point) "Effort"))))
                          ((org-ql-block-header "  < 25 mins\n")))
```

**Comment by alphapapa** [comment]
Oops, I was thinking of this org-super-agenda PR: https://github.com/alphapapa/org-super-agenda/pull/125.  Maybe we should have the same feature in org-ql.

In the meantime, your example using `org-entry-get` is correct.
