### ISSUE TITLE
Weird behavior matching tags when using function arguments

### ISSUE THREAD

**Issue by codygman** [alphapapa/org-ql#85]
The last case demonstrates the issue where a headline is matched even though it's tag doesn't satisfy the predicate. Maybe I'm just using the syntax wrong or misunderstand something.

I'm using:
```
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12)
Org mode version 9.2.6 (release_9.2.6-572-gbe7e88 @ /home/cody/.emacs.d/straight/build/org-plus-contrib/)
org-ql version: d7fe019 (HEAD -> master, origin/master, origin/HEAD) Fix: (helm-source-org-ql-views) Call helm-make-source directly
```

I see there are a few new commits, maybe some of those could address my issue. I'll check and report back.

Org file contents:

```org
* Clubhouse
** TODO item 1                           :1234:
** TODO item 2
```

### org-ql wrongly matches a heading without matching `123456` tag

    (defun incorrectly-matches (number)
      (org-ql "clubhouse.org" (and (tags (number-to-string number)) (level 2))))
    (incorrectly-matches 123456)

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">headline</td>
<td class="org-left">(:raw-value item 1 :begin 13 :end 60 :pre-blank 0 :contents-begin 61 :contents-end 61 :level 2 :priority nil :tags (1234) :todo-keyword TODO :todo-type todo :post-blank 1 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 13 :title (item 1))</td>
</tr>
</tbody>
</table>

**Comment by codygman** [comment]
Perhaps this is because I'm calling a macro within a function?

**Comment by codygman** [comment]
I thought in case it was because `org-ql` is a macro I'd rewrite with `org-ql-select` but I still have the issue.

All results are nil except for `(org-ql-select "clubhouse.org" '(tags (number-to-string 1234)))`

<a id="org73a3824"></a>

# simplified definition only matching tags

    (defun get-local-story-element-by-tag-only (story-number)
      (org-ql-select "clubhouse.org" '(tags (number-to-string story-number))))

    (get-local-story-element-by-tag-only 123456)

    (get-local-story-element-by-tag-only 1234)

    (org-ql-select "clubhouse.org" '(tags (number-to-string 1234)))

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">headline</td>
<td class="org-left">(:raw-value item 1 :begin 13 :end 60 :pre-blank 0 :contents-begin 61 :contents-end 61 :level 2 :priority nil :tags (1234) :todo-keyword TODO :todo-type todo :post-blank 1 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 13 :title (item 1))</td>
</tr>
</tbody>
</table>

    (org-ql-select "clubhouse.org" '(tags (number-to-string 123456)))

**Comment by alphapapa** [comment]
You're making a simple mistake.  Maybe this example will help.  Notice that the number is not present in the result.
```el
(let ((story-number 123456))
  '(tags (number-to-string story-number)))
;;=> (tags (number-to-string story-number))
```

**Comment by codygman** [comment]
Ah, so because I was just copy pasting from the examples I mixed up using/not using macros and ran into the issue you demonstrate above. It wasn't immediately clear to me even with the small example above, but becomes very clear after I run these in ielm:

```
ELISP> (let ((story-number 123456))
  '(number-to-string story-number))
(number-to-string story-number)

ELISP> (let ((story-number 123456))
  (number-to-string story-number))
"123456"
```

For me an example with multiple predicates of each type of the functions `org-ql`, `org-ql-select`, etc would probably have made my mistake obvious. I think that could also help the confusion.

**Comment by alphapapa** [comment]
Yes, quoting is an important concept in Lisp.  It's especially important for `org-ql` since queries are sexps to be evaluated later, not as evaluated arguments to, e.g. `org-ql-select`.
