### ISSUE TITLE
Better deal with entry without parent, child and friend?

### ISSUE THREAD

**Issue by tumashu** [alphapapa/org-ql#91]
Is it possible add a “ORPHAN：” in org-brain-visualize UI, to show all
entry without parent, child and frend?  for I think brain should let things link
each other, it one not link any thing, it shoud be be focus.

```
  (org-ql-select (org-brain-files)
    `(and ,(cadr org-brain--ql-query)
          (property "ID")
          (not (property org-brain-parents-property-name))
          (not (property org-brain-children-property-name))
          (not (property org-brain-friends-property-name)))
    :action #'org-brain--headline-entry-at-point)
```

**Comment by alphapapa** [comment]
Sorry, I can't help you.  `org-brain` is a separate project and I don't use it.

**Comment by tumashu** [comment]
misunderstand?

**Comment by alphapapa** [comment]
What?

**Comment by Kungsgeten** [comment]
@tumashu Its better if you move the issue to the `org-brain` repository.

**Comment by tumashu** [comment]
Sorry sorry .... my fault :-)
