### ISSUE TITLE
'r' for refresh ?

### ISSUE THREAD

**Issue by maxandersen** [alphapapa/org-ql#93]
is it possible to have 'r' refresh the query view ?

I'm using it with sidebar and for now need to go click in the sidebar to get the query view to refresh its contents.

**Comment by alphapapa** [comment]
Hi Max,

Well:

* I guess you mean you're using org-sidebar.  That's a separate package.
* It's Emacs, so you can bind whatever keys you like.
* But IIUC, binding `r` in non-sidebar buffers to refresh the sidebar buffer would probably interfere with `self-insert-command`, i.e. typing `r`.

Maybe a better solution would be to make it easier for you to switch to other windows.  For example, I use `C-2` to switch between windows, so if I have two windows, and one of them is a sidebar, to refresh it, all I'd have to do is press `C-2 r`, which is easy and quick for me.

**Comment by maxandersen** [comment]
okey, its just that every other view in org-mode showing a query/agenda result pressing 'r' seem to refresh the view.

I don't see how it interfere with typing 'r' as the query views are non-editable by default.

**Comment by alphapapa** [comment]
You seem to be talking about different things.  Anyway, the `wip/transient` branch already uses `r` for refreshing `org-ql-view` views.  In the meantime, you can bind keys in your own config however you like.
