### ISSUE TITLE
Getting all headlines that have any tags?

### ISSUE THREAD

**Issue by progfolio** [alphapapa/org-ql#94]
First off, thanks for the great package. I'm working on a package that analyzes a user's org tags and I can't seem to get the query I'm after. I'm just looking for all headlines in org-agenda-files that have tags.

I thought this would do the trick:

```emacs-lisp
(org-ql-select 'org-agenda-files '(tags))
```
but I'm getting headlines that have a :tags property set to nil. Not hard to filter them out, but I'm curious if I just don't have the syntax correct.

Thanks again,
nv

**Comment by alphapapa** [comment]
The issue appears to be that `org-element-heading-parser` does not include inherited tags in its output.  So the headings returned by `(org-ql-select file '(tags))` do have tags, but you'll need to look them up by other means.  For example:
```el
(org-ql-select "~/org/main.org"
  '(tags)
  :action (lambda ()
            (org-get-tags)))
```

**Comment by progfolio** [comment]
Just got a chance to try this. It works, but at the expense of losing the other information about each headline. I'm able to work around this, just thought I'd share that. Thanks again.

**Comment by alphapapa** [comment]
Yes, you'll need to parse the heading element if you also want the other information.  You could do something like this to add the inherited tags:

```el
(org-ql-select "/tmp/test.org"
  '(tags)
  :action '(-let* (((element (properties &as &plist :tags) . children)
                    (org-element-headline-parser (line-end-position)))
                   (tags (push (org-get-tags) tags)))
             (setf properties (plist-put properties :tags tags))
             (cons (list element properties) children)))
```

**Comment by alphapapa** [comment]
@progfolio Note that, since then, the `tags-inherited` predicate was added, so that workaround isn't needed.  https://github.com/alphapapa/org-ql/blob/e41cdb45912f1731b5b060f9e05d011096663655/org-ql.el#L1871
