### ISSUE TITLE
Outline levels in non-lisp queries

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-ql#96]
Hi,

Is it possible to enter *levels* in non-lisp queries? I didn't find an example in README, so I tried `level:4` both in `org-ql-search` and `helm-org-ql`, but it didn't work. Instead, I got the following error:

> rx-repeat: rx ‘repeat’ requires positive integer first arg

This might be because the argument is parsed as a string, not as a number. Could you add an explicit support for specifying levels in non-lisp queries?

**Comment by alphapapa** [comment]
Thanks for catching that!
