### ISSUE TITLE
Error since last update 

### ISSUE THREAD

**Issue by bepolymathe** [alphapapa/org-ql#98]
Hi,  

Since the last update I get this error message when I try to launch a search with Org-ql. 

`byte-code: Symbol’s value as variable is void: crm-local-completion-map`

Any idea ?

**Comment by bepolymathe** [comment]
Reinstalling the package doesn't seem to change anything... it's painful but I don't even know where it comes from... from trying [to configure org-super-agenda](https://www.reddit.com/r/orgmode/comments/fbwkdt/orgsuperagenda_and_tag_option/).
Tomorrow is a working day that will begin without org-ql 😢

**Comment by alphapapa** [comment]
That should fix it.  I broke it with a recent change that was supposed to be an enhancement.  Thank you very much for reporting, otherwise I might not have noticed for a while.

**Comment by bepolymathe** [comment]
That’s great. Thank you 😉
