### ISSUE TITLE
helm-org-ql-map

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-ql#99]
At present, `helm-org-ql-map` is defined as follows:

```emacs-lisp
(defvar helm-org-ql-map
  (let ((map (copy-keymap helm-map))
        (mappings '(
                    "C-x C-s" helm-org-ql-save
                    )))
    (cl-loop for (key fn) on mappings by #'cddr
             do (define-key map (kbd key) fn))
    map)
  "Keymap for `helm-org-ql' sessions.
Based on `helm-map'.")
```

I suppose the correct way to inherit a keymap is to use `make-composed-keymap`. While I was investigating #97, I noticed that additional keybindings added to `helm-map` were not effective in `helm-org-ql-map`. Hopefully this will solve the issue.

**Comment by alphapapa** [comment]
Thanks, Akira, I wasn't even aware of that function.  Please let me know if this fixes it.

**Comment by akirak** [comment]
Thanks, the issue has been fixed.
